export const majorList = [
  "AI융합학부",
  "건축학부",
  "경영학부",
  "경제학과",
  "국어국문학과",
  "국제무역학과",
  "국제법무학과",
  "글로벌미디어학부",
  "글로벌통상학과",
  "금융경제학과",
  "금융학부",
  "기계공학부",
  "기독교학과",
  "독어독문학과",
  "물리학과",
  "미디어경영학과",
  "법학과",
  "벤처경영학과(계약학과)",
  "벤처중소기업학과",
  "복지경영학과(계약학과)",
  "불어불문학과",
  "사학과",
  "사회복지학부",
  "산업·정보시스템공학과",
  "소프트웨어학부",
  "수학과",
  "스포츠학부",
  "언론홍보학과",
  "영어영문학과",
  "예술창작학부 문예창작전공",
  "예술창작학부 영화예술전공",
  "유기신소재·파이버공학과",
  "융합특성화자유전공학부",
  "의생명시스템학부",
  "일어일문학과",
  "전기공학부",
  "전자정보공학부 IT융합전공",
  "전자정보공학부 전자공학전공",
  "정보사회학과",
  "정보통계·보험수리학과",
  "정보통신전자공학부",
  "정치외교학과",
  "중어중문학과",
  "철학과",
  "컴퓨터학부",
  "평생교육학과",
  "행정학부",
  "혁신경영학과(계약학과)",
  "화학공학과",
  "화학과",
  "회계학과",
];

export const gradeList = [
  "12학번",
  "13학번",
  "14학번",
  "15학번",
  "16학번",
  "17학번",
  "18학번",
  "19학번",
  "20학번",
  "21학번",
];

// {
//   major: "",
//   bookList: ["", "", "", "", "", "", "", "", "", ""],
// },

// 학과별 추천 리스트
export const byMajorList = [
  {
    major: "경영학부",
    bookList: [
      "Essentials of investments",
      "경제학원론 =Economics",
      "조직과 리더십 =Organization & leadership",
      "경영전략 =Strategic management",
      "경영학원론",
      "서비스 마케팅 =Service marketing",
      "왜 나는 너를 사랑하는가",
      "참을 수 없는 존재의 가벼움",
      "(친절한) 재무회계 =A gentle introduction to Introduce financial accounting",
      "(친절한) 재무회계=Financial accounting",
    ],
  },
  {
    major: "의생명시스템학부",
    bookList: [
      "An introduction to biostatistics",
      "(레닌저) 생화학",
      "Genetics :a conceptual approach",
      "분자 세포 생물학",
      "Fundamentals of organic chemistry",
      "The immune system",
      "생명과학",
      "(McMurry) 기본유기화학",
      "(알기 쉬운)선형대수",
      "Molecular cell biology",
    ],
  },
  {
    major: "국제법무학과",
    bookList: [
      "국제법 판례 100선 =International law cases",
      "민사소송법",
      "형사소송법",
      "신국제법강의 :이론과 사례",
      "Evidence",
      "Criminal law",
      "International organizations :the politics and processes of global governance",
      "Principles of international business transactions",
      "(객관식) 국제법",
      "(요건사실 중심)분쟁유형별 민사법",
    ],
  },
  {
    major: "소프트웨어학부",
    bookList: [
      "(Do it!) Node.js 프로그래밍 :실제 서버로 구동 가능한 코드로 배운다!",
      "자바 네트워크 프로그래밍",
      "(Do it!) 자바스크립트+제이쿼리 입문  :155개 예재로 기본 잡고, 반응형 웹부터 실무 활용 플러그인까지!",
      "(명품) Java programming",
      "(Do it!) 안드로이드 앱 프로그래밍 :안드로이드 8.0 오레오 버전 반영판!",
      "(명품) JAVA programming",
      "(쉽게 배우는) 데이터 통신과 컴퓨터 네트워크",
      "(Do it!) HTML5+CSS3 웹 표준의 정석",
      "(Do it!) 안드로이드 앱 프로그래밍 :안드로이드 7.0 누가 버전·안드로이드 스튜디오 반영판!",
      "(Rosen의) 이산수학",
    ],
  },
  {
    major: "중어중문학과",
    bookList: [
      "(왜? 라는 질문에 속시원히 답해주는) 중국어 문법책",
      "공자의 생애와 사상",
      "시를 잊은 그대에게",
      "(쉽게 알고 배우는) 易知 한자 :상공회의소 2급 기본서",
      "중국문학사",
      "(쉽게 알고 배우는) 易知 한자 :상공회의소 2급 최종모의고사",
      "참을 수 없는 존재의 가벼움",
      "논어",
      "왜 나는 너를 사랑하는가",
      "(쉽게 알고 배우는) 상공회의소 易知 한자 :2급",
    ],
  },
  {
    major: "화학공학과",
    bookList: [
      "재료과학",
      "(적중) 화공기사",
      "최신공정제어공학 :MATLAB의 활용과 실습",
      "(Kreyszig) 공업수학",
      "Fundamentals of momentum, heat and mass transfer",
      "기초 이동현상론 :운동량, 열 및 물질전달",
      "Fundamentals of organic chemistry",
      "콜로이드와 계면활성제",
      "전기화학",
      "일반화학",
    ],
  },
  {
    major: "행정학부",
    bookList: [
      "정책분석론",
      "정책학원론 =Theories of policy sciences",
      "정책평가론",
      "지방행정론",
      "정책평가:이론과 적용",
      "정책학 :이론과 경험적 연구",
      "행정이론 :행정사와 이론을 중심으로",
      "기획론",
      "정책학원론",
      "정책학원론=Theories of policy sciences",
    ],
  },
  {
    major: "컴퓨터학부",
    bookList: [
      "(명품) Java programming",
      "(Do it!) Node.js 프로그래밍 :실제 서버로 구동 가능한 코드로 배운다!",
      "(Rosen의) 이산수학",
      "(윤성우의 열혈) C++ 프로그래밍",
      "Concepts of programming languages",
      "(윤성우의 열혈) TCP/IP 소켓 프로그래밍",
      "Java의 정석",
      "코딩 인터뷰 완전 분석   :189가지 프로그래밍 문제와 해법",
      "(2017) 정보처리기사 :실기(산업기사 포함) 기본서",
      "(모던 웹을 위한) Node.js 프로그래밍",
    ],
  },
  {
    major: "혁신경영학과(계약학과)",
    bookList: [
      "Principles of marketing",
      "강아지똥",
      "미녀는 괴로워",
      "(모던 웹을 위한) JavaScript jQuery 입문",
      "말아톤",
      "(학예사를 위한) 전시기획입문",
      "시크릿 Bangkok :로컬이 인정하는 방콕의 비밀 명소",
      "스프링 5 레시피 :스프링 애플리케이션 개발에 유용한 161가지 문제 해결 기법",
      "뽑히는 자기소개서",
      "코딩 인터뷰 완전 분석   :189가지 프로그래밍 문제와 해법",
    ],
  },
  {
    major: "독어독문학과",
    bookList: [
      "향수 :어느 살인자의 이야기 :파트리크 쥐스킨트 장편소설",
      "데미안",
      "모래 사나이",
      "파우스트",
      "토니오 크뢰거 :토마스 만 단편선",
      "깊이에의 강요",
      "獨逸文學思潮史",
      "詩學",
      "니벨룽겐의 노래",
      "(북유럽 신화)에다 :게르만 민족의 신화, 영웅전설, 생활의 지혜",
    ],
  },
  {
    major: "예술창작학부 영화예술전공",
    bookList: [
      "시나리오 어떻게 쓸 것인가",
      "영화조명핸드북",
      "왜 나는 너를 사랑하는가",
      "참을 수 없는 존재의 가벼움",
      "이갈리아의 딸들",
      "친절한 금자씨",
      "데미안",
      "예술가여, 무엇이 두려운가!",
      "사랑의 기술",
      "시나리오란 무엇인가",
    ],
  },
  {
    major: "정보사회학과",
    bookList: [
      "사이버범죄학 =Cyber criminology :원인/유형/대책",
      "사회조사방법론",
      "이기적 유전자 :진화론의 새로운 패러다임",
      "국가란 무엇인가",
      "사회조사 분석사 2급 :2차 실기 :한권으로 끝내기",
      "이기적 유전자",
      "사회조사분석사 +α :2급 실기 필답형(논술형)",
      "사회조사분석사 :2급 필기 :한권으로 올인하기",
      "멋진 신세계",
      "(SPSS) 사회조사분석사 :2급 2차 실기",
    ],
  },
  {
    major: "스포츠학부",
    bookList: [
      "스포츠마케팅 =Sport marketing",
      "요가 아나토미 :해부학적으로 쉽게 배우는 요가",
      "아헹가 요가:몸과 영혼의 해탈에 이르는 길",
      "(Enger) 생명과학",
      "(NASM의) 퍼스널 트레이닝",
      "달과 6펜스",
      "사회체육지도론",
      "스타팅 스트렝스 :기본 바벨 훈련",
      "현대여가학=Modern leisure studies",
      "(생활체육지도자용) 퍼펙트 웨이트트레이닝",
    ],
  },
  {
    major: "사학과",
    bookList: [
      "인생:위화 장편소설",
      "東洋史槪論",
      "한국 고고학 강의",
      "서양사강의",
      "중국사",
      "한국건축의 역사",
      "西洋史槪論",
      "역사란 무엇인가",
      "동양사개론",
      "아틀라스 중국사",
    ],
  },
  {
    major: "수학과",
    bookList: [
      "수학교육학신론",
      "Linear algebra and its applications",
      "선형 대수학과 그 응용",
      "Elementary number theory",
      "보험수리학 = Actuarial mathematics",
      "현대대수학",
      "Numerical mathematics and computing",
      "일반위상수학:이론과 연습",
      "Schaum's outline of theory and problems of set theory and related topics",
      "Mathematics for finance :an introduction to financial engineering",
    ],
  },
  {
    major: "경제학과",
    bookList: [
      "(시사와 함께하는) 거시경제학",
      "미시경제학",
      "미시경제학 :수학노트와 연습문제 해답",
      "재정학 =Public finance",
      "경제학 연습 :미시편",
      "Introduction to econometrics",
      "금융경제론 =(The) economics of money, banking and financial markets",
      "거시경제학",
      "생활경제 =Economy and life",
      "게임이론 길라잡이",
    ],
  },
  {
    major: "예술창작학부 문예창작전공",
    bookList: [
      "감시와 처벌:감옥의 역사",
      "참을 수 없는 존재의 가벼움",
      "하녀들",
      "인형의 집:헨리크 입센 희곡선집",
      "금각사",
      "입속의 검은 잎:기형도 시집",
      "대성당 :레이먼드 카버 소설",
      "단지 유령일 뿐",
      "오디세이아 :트로이 전쟁, 그 후 10년의 이야기",
      "변신 :카프카 단편선",
    ],
  },
  {
    major: "금융경제학과",
    bookList: [
      "미시경제학",
      "미시경제학 :수학노트와 연습문제 해답",
      "증권투자론 =Investments ＆ security analysis",
      "미시경제학 =Microeconomics",
      "(시사와 함께하는) 거시경제학",
      "거시경제학",
      "이갈리아의 딸들",
      "맨큐의 경제학",
      "(글로벌 시대의) 국제금융론 =International finance",
      "미시경제학:수학노트와 연습문제 해답",
    ],
  },
  {
    major: "화학과",
    bookList: [
      "무기화학",
      "(레닌저) 생화학",
      "물리화학실험",
      "유기화학실험",
      "Atkins' physical chemistry",
      "분석화학실험=Experimental analytical chemistry",
      "Student solutions manual to accompany Atkins' physical chemistry",
      "Lehninger principles of biochemistry",
      "(파비아의) 분광학강의",
      "Inorganic chemistry",
    ],
  },
  {
    major: "금융학부",
    bookList: [
      "맨큐의 경제학",
      "Options, futures, and other derivatives",
      "선물·옵션 투자의 이론과 전략",
      "파생상품의 평가와 헷징전략",
      "Principles of economics",
      "금융기관론 =Financial institutions management",
      "죽은 경제학자의 살아있는 아이디어",
      "Fundamentals of investments :valuation and management",
      "돈, 뜨겁게 사랑하고 차갑게 다루어라",
      "Financial markets and institutions",
    ],
  },
  {
    major: "AI융합학부",
    bookList: [
      "(알기 쉬운)선형대수",
      "UNIX 고급 프로그래밍",
      "전자회로",
      "컴퓨터 구조 및 설계 :하드웨어/소프트웨어 인터페이스",
      "Java의 정석",
      "(윤성우의 열혈) C++ 프로그래밍",
      "안드로이드 앱 프로그래밍 :T아카데미의 명강의를 한 권에 담았다!",
      "ROS 로봇 프로그래밍",
      "Digital design, with RTL design, VHDL, and Verilog",
      "(모두를 위한) 실용 전자공학 :기초부터 실무까지",
    ],
  },
  {
    major: "국제무역학과",
    bookList: [
      "거시경제학 =Macro economics",
      "마케팅관리론",
      "(新) 국제경제법 =International economic law",
      "(이훈영 교수의) 마케팅 조사론",
      "(프렌즈) 유럽 :베스트 시티 45 =Europe : best city 45",
      "총, 균, 쇠 :무기, 병균, 금속은 인류의 운명을 어떻게 바꿨는가",
      "중국경제론 =China economy",
      "국제운송물류 =International transportation & logistics",
      "수학 세상 가볍게 읽기",
      "신무역보험론",
    ],
  },
  {
    major: "국어국문학과",
    bookList: [
      "(최유찬의) 문예사조의 이해",
      "개념어 사전:인터넷에서도 검색할 수 없는 생생한 지식의 보물 창고",
      "국어음운론 개설",
      "한국현대문학사",
      "호모 루덴스:놀이와 문화에 관한 한 연구",
      "문학비평 용어사전",
      "나는 나를 파괴할 권리가 있다 :김영하 장편소설",
      "이갈리아의 딸들",
      "배비장전",
      "장끼전",
    ],
  },
  {
    major: "산업·정보시스템공학과",
    bookList: [
      "Introduction to operations research",
      "품질경영",
      "인간공학",
      "(No. 1 배극윤의) 품질경영기사 :필기",
      "Supply chain management :strategy, planning, and operation",
      "일반화학",
      "(No.1 배극윤의) 품질경영 기사 필기 =Engineer quality management",
      "공급사슬관리 =Supply chain management",
      "Arena를 이용한 시뮬레이션",
      "SQL 전문가 가이드 =(The)guide for SQL professional",
    ],
  },
  {
    major: "미디어경영학과",
    bookList: [
      "이갈리아의 딸들",
      "컴퓨터 그래픽스 배움터",
      "(최신)디지털미디어 원리 및 프로그래밍",
      "사랑의 기술",
      "(친절한) 회계원리",
      "Probability, random variables, and random signal principles",
      "이기적 유전자",
      "(에센스) 재무관리 =Financial management",
      "기독교와 현대사회",
      "(KS 규격에 따른) AutoCAD와 기계설계제도",
    ],
  },
  {
    major: "영어영문학과",
    bookList: [
      "캔터베리 이야기",
      "위대한 개츠비",
      "주홍글씨",
      "세일즈맨의 죽음",
      "English syntax and argumentation",
      "시스터 캐리",
      "유토피아",
      "검은 고양이 ...外",
      "프랑스 중위의 여자:존 파울즈 장편소설",
      "English :one tongue, many voices",
    ],
  },
  {
    major: "정치외교학과",
    bookList: [
      "역사란 무엇인가",
      "침묵",
      "죽은 경제학자의 살아있는 아이디어",
      "군주론",
      "감시와 처벌:감옥의 역사",
      "한국정치론 =Understanding Korean politics",
      "자유론",
      "제도분석 :이론과 쟁점",
      "국가란 무엇인가",
      "국제관계학:인간과 세계 그리고 정치",
    ],
  },
  {
    major: "법학과",
    bookList: [
      "국제법 판례 100선 =International law cases",
      "노동법 =Labour law",
      "국제법 판례 100선",
      "노동법",
      "(에센스) 노동법",
      "형사소송법",
      "행정법강의",
      "행정법강의 =Administrative law",
      "債權各論",
      "(객관식) 국제법",
    ],
  },
  {
    major: "회계학과",
    bookList: [
      "세법개론",
      "(IFRS) 중급회계 =Intermediate accounting",
      "(2019) 세법개론 =Tax law",
      "정부회계학 :국가회계와 지방회계 =Governmental accounting",
      "IFRS 중급 회계 =International financial reporting standards intermediate accounting",
      "IFRS 중급회계 =International financial reporting standards  intermediate accounting",
      "IFRS 고급회계 =Advanced accounting",
      "재무관리 =Financial management",
      "(2018) 세법개론",
      "경제학 연습 :거시편",
    ],
  },
  {
    major: "불어불문학과",
    bookList: [
      "어두운 상점들의 거리 :파트릭 모디아노 장편소설",
      "노트르담 드 파리",
      "피가로의 결혼",
      "참을 수 없는 존재의 가벼움",
      "델프 =DELF B2",
      "위대한 개츠비",
      "랑송 佛文學史",
      "이방인",
      "페드르",
      "미라보 다리",
    ],
  },
  {
    major: "글로벌통상학과",
    bookList: [
      "맨큐의 경제학",
      "해상보험",
      "중국경제론 =China economy",
      "(한주섭 교수의 최신) 화환신용장론",
      "(新) 국제경제법 =International economic law",
      "글로벌경영 =Global business management",
      "Global marketing",
      "총, 균, 쇠 :무기, 병균, 금속은 인류의 운명을 어떻게 바꿨는가",
      "미시경제학",
      "거시경제학 =Macro economics",
    ],
  },
  {
    major: "일어일문학과",
    bookList: [
      "구로사와 아키라의 영화세계",
      "참을 수 없는 존재의 가벼움",
      "설국",
      "상실의 시대",
      "구토",
      "영화의 이해",
      "국화와 칼:일본 문화의 틀",
      "경제학원론 =Economics",
      "침묵",
      "사랑의 기술",
    ],
  },
  {
    major: "언론홍보학과",
    bookList: [
      "매스미디어 연구방법론",
      "광고매체기획론 =Advertising media planning",
      "방송학 개론",
      "뉴미디어와 정보사회",
      "인간커뮤니케이션과 미디어 :소통공간의 확장",
      "광고학개론 =AnIntroduction to advertising",
      "사랑의 기술",
      "방송학개론",
      "데미안",
      "대중문화의 이해",
    ],
  },
  {
    major: "벤처중소기업학과",
    bookList: [
      "글로벌경영 =Global business management",
      "(친절한) 재무회계 =A gentle introduction to Introduce financial accounting",
      "전략적 브랜드관리=Strategic brand management :이론과 응용",
      "부자 아빠 가난한 아빠      :부자들이 들려주는 '돈'과 '투자'의 비밀",
      "왜 나는 너를 사랑하는가",
      "위대한 개츠비",
      "(이훈영교수의) 연구조사방법론=Research methodology",
      "전략적 관리회계 =Strategic management accounting",
      "경제학 연습 :미시편",
      "멋진 신세계",
    ],
  },
  {
    major: "융합특성화자유전공학부",
    bookList: [
      "신약성서는 오늘 우리에게 이렇게 증언한다:월요신학서당 편",
      "변신 :카프카 단편선",
      "영화로 읽는 정신분석  :김서영의 치유하는 영화읽기",
      "(새로 만든) 먼나라 이웃나라",
      "기독교와 동성애",
      "역사란 무엇인가",
      "이방인",
      "수수께끼 풀이는 저녁 식사 후에",
      "예술이란 무엇인가",
      "나르치스와 골드문트",
    ],
  },
  {
    major: "정보통신전자공학부",
    bookList: [
      "정보 보안 개론 :한 권으로 배우는 보안 이론의 모든 것",
      "전자기학",
      "SK 그룹 SKCT :SK종합역량검사 :실전모의고사",
      "Eagle CAD 배우기",
      "Principles of communication :systems, modulation, and noise",
      "(이렇게 기막힌 적중률 2017) 정보처리기사 :필기 기본서",
      "(최적합) 네트워크관리사 1·2급 필기 =Network Administrator :최고의 적중률로 합격을 보장하는 국가공인 2017년 최신 기출문제 수록",
      "무선설비기사 =Radio operator :과년도",
      "무선설비기사 :과년도 :한국방송통신전파진흥원 필기시험 집중 대비서",
      "무궁화 꽃이 피었습니다 :김진명 장편소설",
    ],
  },
  {
    major: "건축학부",
    bookList: [
      "현대 건축 :비판적 역사",
      "(10개년) 건축기사 :과년도문제상세해설",
      "건축, 음악처럼 듣고 미술처럼 보다 :인문적 건축이야기",
      "꿈돌이의 라이노 5 :Rhino 건축 모델링 A to Y",
      "건축구조역학",
      "빈자의 미학 =Beauty of poverty",
      "강구조 설계",
      "건축기사 4주완성",
      "건축기사실기 :2017.1.1 출제기준 변경에 따른 예상문제 총정리",
      "(그림으로 알기 쉽게 해설한) 인테리어 도면 보는 법과 그리는 법",
    ],
  },
  {
    major: "전자정보공학부 전자공학전공",
    bookList: [
      "통신이론",
      "Semiconductor physics and devices :basic principles",
      "전자기학 =Engineering electromagnetics",
      "미분적분학 =Calculus",
      "디지털 신호처리:원리, 알고리즘, 응용",
      "CMOS digital integrated circuits :analysis and design",
      "마이크로파 공학",
      "신호 및 시스템",
      "Introduction to microelectronic fabrication",
      "Advanced engineering mathematics",
    ],
  },
  {
    major: "물리학과",
    bookList: [
      "기초전자기학",
      "해석역학",
      "광학",
      "Mathematical methods in the physical sciences",
      "핵 및 입자물리학",
      "An introduction to computer simulation methods :applications to physical systems",
      "Introduction to solid state physics",
      "(과학도를 위한)전자공학",
      "양자역학",
      "Introduction to electrodynamics",
    ],
  },
  {
    major: "벤처경영학과(계약학과)",
    bookList: ["경제학원론 =Economics"],
  },
  {
    major: "사회복지학부",
    bookList: [
      "지역사회복지론 =Community welfare",
      "사회복지법제론",
      "청소년복지론",
      "청소년복지론=Social welfare with youth",
      "사회복지법제론 =Social welfare and law",
      "사회복지조사방법론",
      "해결을 위한 면접",
      "(에센스) 사회복지조사방법론",
      "새로 쓰는 여성복지론 :쟁점과 실천",
      "학교사회복지론 =School social work",
    ],
  },
  {
    major: "정보통계·보험수리학과",
    bookList: [
      "수리통계학",
      "(2018) 보험수학 perfect 정리 :보험계리사 1차시험 대비",
      "표본조사의 이해와 활용",
      "보험수리학 = Actuarial mathematics",
      "Elementary survey sampling",
      "Loss models :from data to decisions",
      "범주형 자료분석 개론",
      "(SOA exam FM) 금융수리",
      "통계적 품질관리",
      "(2018) 보험수리학 Perfect 정리: 보험계리사 2차시험 대비",
    ],
  },
  {
    major: "전자정보공학부 IT융합전공",
    bookList: [
      "통신이론",
      "(먼저 배우는) DSP",
      "(Hayt의) 전자기학",
      "신호 및 시스템",
      "(객체지향 원리로 이해하는) Absolute C++",
      "미분적분학 =Calculus",
      "Engineering electromagnetics",
      "Computer networking :a top-down approach",
      "ARM system－on－chip 구조",
      "(윤성우의 열혈) TCP/IP 소켓 프로그래밍",
    ],
  },
  {
    major: "평생교육학과",
    bookList: [
      "평생교육경영론",
      "리더십 :이론과 실제",
      "101 ways to make training active",
      "E-learning by design",
      "(평생학습사회 실현을 위한) 성인학습 및 상담 =Adult learning and counselling",
      "화성에서 온 남자 금성에서 온 여자",
      "데미안",
      "경영정보시스템",
      "왜 나는 너를 사랑하는가",
      "사랑의 기술",
    ],
  },
  {
    major: "복지경영학과(계약학과)",
    bookList: [
      "(새로 쓴) 원숭이도 이해하는 자본론 :세상에서 가장 쉬운 임승수의 마르크스 자본론 강의",
      "Everyday Talking :abroad",
      "방콕 =Bankok",
      "잉글리시 리스타트 =English restart: basic",
    ],
  },
  {
    major: "기독교학과",
    bookList: [
      "기독교 조직신학 개론 :이해를 추구하는 신앙",
      "기독교 세계관과 현대사상",
      "(아는 만큼 행복이 커지는) 가족의 심리학",
      "종교사회학",
      "하나님 나라 신학으로 읽는 모세오경",
      "한국 기독교의 역사",
      "현대교회사 :쉽게 이야기체로 풀어쓴 흥미로운 역사서",
      "성경을 어떻게 읽을 것인가",
      "철학과 굴뚝청소부:데카르트에서 들뢰즈까지 : 근대철학의 경계들",
      "현대 사회 문제와 그리스도인의 책임",
    ],
  },
  {
    major: "기계공학부",
    bookList: [
      "(최신) 공업열역학",
      "(공학도를 위한) 길잡이 공업수학 문제풀이집",
      "유체역학",
      "(최신) 기계설계 =Mechanical engineering design",
      "연료전지개론",
      "Engineering fundamentals of the internal combustion engine",
      "(Kreyszig) 공업수학",
      "(공학도를 위한) 길잡이 공업수학",
      "Mechanics of Materials",
      "공업재료가공학",
    ],
  },
  {
    major: "글로벌미디어학부",
    bookList: [
      "(최신)디지털미디어 원리 및 프로그래밍",
      "컴퓨터 그래픽스 배움터",
      "(Rosen의) 이산수학",
      "Foundations of algorithms",
      "New media",
      "왜 나는 너를 사랑하는가",
      "(Do it!) Node.js 프로그래밍 :실제 서버로 구동 가능한 코드로 배운다!",
      "Discrete mathematics and its applications",
      "(모던 웹을 위한) JavaScript jQuery 입문",
      "(C언어로 쉽게 풀어쓴) 자료 구조",
    ],
  },
  {
    major: "전기공학부",
    bookList: [
      "전자회로",
      "Digital design with CPLD applications and VHDL",
      "Power systems analysis",
      "(최신) 배전시스템 공학=Distribution engineering",
      "전자기학",
      "최신제어시스템",
      "미분적분학 =Calculus",
      "전력계통 :해석 및 설계",
      "(PSpice를 활용한)전력전자공학",
      "Electronic devices and circuit theory",
    ],
  },
  {
    major: "유기신소재·파이버공학과",
    bookList: [
      "섬유재료학",
      "기능성 섬유가공 =Functional finishs",
      "섬유학",
      "무기화학",
      "(알기쉬운) 통계학",
      "(파비아의) 분광학강의",
      "섬유기초기술 =Textile basic technology",
      "분광학의 이해",
      "Introduction to spectroscopy",
      "(McMurry) 기본유기화학",
    ],
  },
  {
    major: "철학과",
    bookList: [
      "중국철학사",
      "한국철학사상사",
      "(플라톤의) 국가(正體)",
      "감시와 처벌:감옥의 역사",
      "국가",
      "구토",
      "인식론의 역사",
      "대학·중용",
      "사랑의 기술",
      "니코마코스 윤리학",
    ],
  },
];

// 학번별 추천 리스트
export const byGradeList = [
  {
    grade: "12학번",
    bookList: [
      "총, 균, 쇠 :무기, 병균, 금속은 인류의 운명을 어떻게 바꿨는가",
      "왜 나는 너를 사랑하는가",
      "(2주 만에 끝내는) 해커스 OPIc :advanced 공략",
      "경제학 연습 :미시편",
      "국가란 무엇인가",
      "해커스 토익 실전 1000제 :reading :해설집.1",
      "(조민혁의) 합격을 부르는 자소서",
      "세법개론",
      "(친절한) 재무회계 =A gentle introduction to Introduce financial accounting",
      "미시경제학",
    ],
  },
  {
    grade: "13학번",
    bookList: [
      "총, 균, 쇠 :무기, 병균, 금속은 인류의 운명을 어떻게 바꿨는가",
      "왜 나는 너를 사랑하는가",
      "참을 수 없는 존재의 가벼움",
      "데미안",
      "미분적분학 =Calculus",
      "(조민혁의) 합격을 부르는 자소서",
      "(2주 만에 끝내는) 해커스 OPIc :advanced 공략",
      "국가란 무엇인가",
      "진로 탐색 및 직업 선택 :NCS 직업기초능력의 이해와 실습",
      "경제학 연습 :미시편",
    ],
  },
  {
    grade: "14학번",
    bookList: [
      "참을 수 없는 존재의 가벼움",
      "미분적분학 =Calculus",
      "왜 나는 너를 사랑하는가",
      "데미안",
      "총, 균, 쇠 :무기, 병균, 금속은 인류의 운명을 어떻게 바꿨는가",
      "국제법 판례 100선 =International law cases",
      "미시경제학",
      "미시경제학 :수학노트와 연습문제 해답",
      "전자기학",
      "노동법",
    ],
  },
  {
    grade: "15학번",
    bookList: [
      "왜 나는 너를 사랑하는가",
      "데미안",
      "이갈리아의 딸들",
      "참을 수 없는 존재의 가벼움",
      "국제법 판례 100선 =International law cases",
      "위대한 개츠비",
      "(2주 만에 끝내는) 해커스 OPIc :advanced 공략",
      "국제법 판례 100선",
      "진로 탐색 및 직업 선택 :NCS 직업기초능력의 이해와 실습",
      "총, 균, 쇠 :무기, 병균, 금속은 인류의 운명을 어떻게 바꿨는가",
    ],
  },
  {
    grade: "16학번",
    bookList: [
      "참을 수 없는 존재의 가벼움",
      "사랑의 기술",
      "왜 나는 너를 사랑하는가",
      "이갈리아의 딸들",
      "국제법 판례 100선 =International law cases",
      "데미안",
      "미시경제학",
      "(시사와 함께하는) 거시경제학",
      "미시경제학 :수학노트와 연습문제 해답",
      "(최적합) ACA 포토샵CC =Adobe Certified Associate & Photoshop CC :국제인증 자격증",
    ],
  },
  {
    grade: "17학번",
    bookList: [
      "왜 나는 너를 사랑하는가",
      "사랑의 기술",
      "위대한 개츠비",
      "이갈리아의 딸들",
      "멋진 신세계",
      "참을 수 없는 존재의 가벼움",
      "이기적 유전자",
      "데미안",
      "맨큐의 경제학",
      "이기적 유전자 :진화론의 새로운 패러다임",
    ],
  },
  {
    grade: "18학번",
    bookList: [
      "이기적 유전자 :진화론의 새로운 패러다임",
      "역사란 무엇인가",
      "이갈리아의 딸들",
      "참을 수 없는 존재의 가벼움",
      "왜 나는 너를 사랑하는가",
      "이기적 유전자",
      "사랑의 기술",
      "자유론",
      "총, 균, 쇠 :무기, 병균, 금속은 인류의 운명을 어떻게 바꿨는가",
      "데미안",
    ],
  },
  {
    grade: "19학번",
    bookList: [
      "데미안",
      "맨큐의 경제학",
      "(Rosen의) 이산수학",
      "왜 나는 너를 사랑하는가",
      "기독교 조직신학 개론 :이해를 추구하는 신앙",
      "침묵",
      "역사란 무엇인가",
      "일반화학",
      "참을 수 없는 존재의 가벼움",
      "미분적분학 =Calculus",
    ],
  },
  {
    grade: "20학번",
    bookList: [
      "멋진 신세계",
      "역사란 무엇인가",
      "(알기 쉬운)선형대수",
      "(Kotler의) 마케팅 원리",
      "나는 소망한다 내게 금지된 것을 :양귀자 장편소설",
      "데미안",
      "경영학의 이해",
      "(명품) Java programming",
      "미시경제학 =Microeconomics",
      "경제학원론 =Economics",
    ],
  },
  {
    grade: "21학번",
    bookList: [
      "역사란 무엇인가",
      "미분적분학 =Calculus",
      "왜 나는 너를 사랑하는가",
      "위대한 개츠비",
      "올 댓 매너 =All that manner :글로벌매너, 비즈니스매너, 공공생활매너",
      "멋진 신세계",
      "철학의 주요문제에 대한 논쟁",
      "문명의 충돌 :세계질서 재편의 핵심 변수는 무엇인가",
      "맨큐의 경제학",
      "이기적 유전자 :진화론의 새로운 패러다임",
    ],
  },
];

// 외부데이터 활용한
/* 학과 학번별 */

export const byMajorAndGradeList = [
  {
    major: "AI융합학부",
    grade: "12학번",
    bookList: [
      "사랑의 기술",
      "(예제 중심의) 파이썬3: 쉽고 재미있는 프로그래밍 언어",
      "안드로이드 앱 프로그래밍 :T아카데미의 명강의를 한 권에 담았다!",
      "(빠르게 활용하는) 파이썬 3.2 프로그래밍 =Paython 3.2 programing",
      "C programming :a modern approach",
      "Computer systems :a programmer's perspective",
      "미분적분학 =Calculus",
      "(예제중심의) 이산수학",
      "Linear algebra and its applications",
      "GIS 지리정보학 :이론과 실습",
    ],
  },

  {
    major: "AI융합학부",
    grade: "13학번",
    bookList: [
      "(세계 속의)음식문화",
      "몽고디비 인 액션 =MongoDB in action",
      "(쉽게 풀어쓴) C언어 express",
      "Operating system concepts update",
      "Operating system concepts",
      "(나와 상대를 찾아가는 여정) 에니어그램 이론과 실제 :아홉가지 성격유형",
      "군주론",
      "Java의 정석",
      "스크루테이프의 편지",
      "(알기 쉬운)선형대수",
    ],
  },
  {
    major: "AI융합학부",
    grade: "14학번",
    bookList: [
      "Linux kernel development",
      "이산수학",
      "파이썬 웹 프로그래밍: Django(장고)로 배우는 쉽고 빠른 웹 개발",
      "Embedded Linux primer :a practical real-world approach",
      "(개념잡이) 전자회로",
      "회로이론",
      "전자회로공학",
      "Advanced programming in the UNIX environment",
      "UNIX 고급 프로그래밍",
      "(객체지향 원리로 이해하는) Absolute C++",
    ],
  },
  {
    major: "AI융합학부",
    grade: "15학번",
    bookList: [
      "UNIX 고급 프로그래밍",
      "ROS 로봇 프로그래밍",
      "리눅스 시스템 프로그래밍",
      "(윤성우의 열혈) C++ 프로그래밍",
      "컴퓨터 네트워킹:하향식 접근",
      "전자회로",
      "(Do it!) 자바스크립트+제이쿼리 입문  :155개 예재로 기본 잡고, 반응형 웹부터 실무 활용 플러그인까지!",
      "컴퓨터 구조 및 설계 :하드웨어/소프트웨어 인터페이스",
      "C로 배우는 쉬운 자료구조",
      "리눅스 커널 내부구조 :리눅스 해커를 위한 지침서",
    ],
  },
  {
    major: "AI융합학부",
    grade: "16학번",
    bookList: [
      "Java의 정석",
      "(알기 쉬운)선형대수",
      "보통의 존재 :이석원 산문집",
      "(윤성우의 열혈) C++ 프로그래밍",
      "ROS 로봇 프로그래밍",
      "(모두를 위한) 실용 전자공학 :기초부터 실무까지",
      "사피엔스 :리커버북",
      "(그림으로 쉽게 설명하는) 안드로이드 프로그래밍 =Android programming",
      "(Do it!) Node.js 프로그래밍 :실제 서버로 구동 가능한 코드로 배운다!",
      "해커스 新 토익 보카 =Vocabulary",
    ],
  },
  {
    major: "AI융합학부",
    grade: "17학번",
    bookList: [
      "(알기 쉬운)선형대수",
      "파이썬 for beginner",
      "(Android Studio를 활용한) 안드로이드 프로그래밍 :Android 10.0(Q) 지원, Android Studio 3.x 사용",
      "(모던 웹을 위한) Node.js 프로그래밍",
      "C로 배우는 쉬운 자료구조",
      "컴퓨터 구조 및 설계 :하드웨어/소프트웨어 인터페이스",
      "전자회로",
      "Digital design, with RTL design, VHDL, and Verilog",
      "(C++로 구현하는) 자료구조와 알고리즘",
      "보 보안 개론   :한 권으로 배우는 핵심 보안 이론",
    ],
  },
  {
    major: "AI융합학부",
    grade: "18학번",
    bookList: [
      "안드로이드 앱 프로그래밍 :T아카데미의 명강의를 한 권에 담았다!",
      "(Do it!) 안드로이드 앱 프로그래밍 :안드로이드 7.0 누가 버전·안드로이드 스튜디오 반영판!",
      "(C++ API) OpenCV 프로그래밍 :OpenCV로 배우는 디지털 영상처리",
      "(Android Studio를 활용한) 안드로이드 프로그래밍 :Android 10.0(Q) 지원, Android Studio 3.x 사용",
      "(Do it!)안드로이드 앱 프로그래밍 :세상의 속도를 따라잡고 싶다면",
      "(최적합) ACA 포토샵CC =Adobe Certified Associate & Photoshop CC :국제인증 자격증",
      "UNIX 고급 프로그래밍",
      "(모두를 위한) 실용 전자공학 :기초부터 실무까지",
      "헬로! 파이썬 프로그래밍: 쉽고 재미있게 프로그래밍 배우기",
      "리더십 파이프라인",
    ],
  },
  {
    major: "AI융합학부",
    grade: "19학번",
    bookList: [
      "(윤성우의 열혈) C 프로그래밍",
      "해커스 텝스 보카",
      "(Rosen의) 이산수학",
      "(C++ API) OpenCV 프로그래밍 :OpenCV로 배우는 디지털 영상처리",
      "래디컬 페미니즘: 성별계급제를 꿰뚫는 시선",
      "미분적분학 =Calculus",
      "정보 보안 개론   :한 권으로 배우는 핵심 보안 이론",
      "(윤성우의 열혈) C++ 프로그래밍",
      "(21세기) 먼나라 이웃나라",
      "AutoCAD 도면그리는 법 :AutoCAD 실기/실습",
    ],
  },
  {
    major: "AI융합학부",
    grade: "20학번",
    bookList: [
      "(최적합) ACA 포토샵CC =Adobe Certified Associate & Photoshop CC :국제인증 자격증",
      "공학수학",
      "나의 첫 머신러닝/딥러닝 :파이썬으로 구현해보는 필수 머신러닝/딥러닝 알고리즘",
      "일본어 들어가기",
      "파이썬 머신러닝 완벽 가이드 :다양한 캐글 예제와 함께 기초 알고리즘부터 최신 기법까지 배우는",
      "범죄 수학 =(A) curious history of mathematics",
      "(알기 쉬운)선형대수",
      "(이공학도를 위한) 확률과 통계",
      "(Rosen의) 이산수학",
      "(객체지향 원리로 이해하는) Absolute C++",
    ],
  },
  {
    major: "AI융합학부",
    grade: "21학번",
    bookList: [
      "(4차 산업혁명 시대의) 이산수학",
      "파이썬 웹 프로그래밍: Django(장고)로 배우는 쉽고 빠른 웹 개발",
      "HTML5 & CSS3 사전",
      "역사란 무엇인가",
      "(Do it!) 자바스크립트+제이쿼리 입문  :155개 예재로 기본 잡고, 반응형 웹부터 실무 활용 플러그인까지!",
    ],
  },
  {
    major: "전자정보공학부 IT융합전공",
    grade: "12학번",
    bookList: [
      "(2주 만에 끝내는) 해커스 OPIc start :intermediate 공략",
      "(이렇게 기막힌 적중률 2017) 정보처리기사 :필기 기본서",
      "(Rosen의) 이산수학",
      "RF회로의 기초",
      "Java의 정석",
      "Computer networking     :a top-down approach",
      "컴퓨터 사이언스 :새내기를 위한 최신 컴퓨터 개론",
      "(쉽게 배우는) MATLAB 입문과 활용 :R2016a",
      "(Matlab과 simulink를 이용한) 통신시스템 및 디지털 통신실습",
      "무선설비기사 =Radio operator :필기",
    ],
  },
  {
    major: "전자정보공학부 IT융합전공",
    grade: "13학번",
    bookList: [
      "Microelectronic circuits",
      "(이렇게 기막힌 적중률 2017) 정보처리기사 :필기 기본서",
      "SQL 전문가 가이드 =(The)guide for SQL professional",
      "(마두식의 중등수학 올림피아를 위한) 정수론",
      "C로 배우는 쉬운 자료구조",
      "전자기학",
      "Computer networking     :a top-down approach",
      "Computer networking :a top-down approach",
      "통신이론",
      "(No plan! No problem!) Enjoy 도쿄",
    ],
  },
  {
    major: "전자정보공학부 IT융합전공",
    grade: "14학번",
    bookList: [
      "컴퓨터시스템구조",
      "(먼저 배우는)DSP",
      "정보통신기사 =Information communication craftman: 과년도",
      "Foundations of algorithms using C++ pseudocode",
      "(먼저 배우는) DSP",
      "통신이론",
      "(객체지향 원리로 이해하는) Absolute C++",
      "위대한 개츠비",
      "전자기학",
      "구해줘 :기욤 뮈소 장편소설",
    ],
  },
  {
    major: "전자정보공학부 IT융합전공",
    grade: "15학번",
    bookList: [
      "(먼저 배우는) DSP",
      "통신이론",
      "(Hayt의) 전자기학",
      "(객체지향 원리로 이해하는) Absolute C++",
      "미분적분학 =Calculus",
      "Fundamentals of electric circuits",
      "(MATLAB 실습으로 배우는)통신시스템 및 디지털통신",
      "운영체제 :그림으로 배우는 구조와 원리",
      "핸즈온 머신러닝",
      "Digital design, with RTL design, VHDL, and Verilog",
    ],
  },
  {
    major: "전자정보공학부 IT융합전공",
    grade: "16학번",
    bookList: [
      "ARM system－on－chip 구조",
      "(윤성우의 열혈) TCP/IP 소켓 프로그래밍",
      "CMOS digital integrated circuits :analysis and design",
      "(Hayt의) 전자기학",
      "운영체제 :그림으로 배우는 구조와 원리",
      "C로 배우는 쉬운 자료구조",
      "Foundations of algorithms",
      "선형대수학과 응용",
      "(먼저 배우는) DSP",
      "Computer networking :a top-down approach",
    ],
  },
  {
    major: "전자정보공학부 IT융합전공",
    grade: "17학번",
    bookList: [
      "왜 나는 너를 사랑하는가",
      "신호 및 시스템",
      "정보통신기사 =Information communication craftman :과년도",
      "An introduction to Semiconductor devices",
      "(Hayt의) 전자기학",
      "정보통신기사 =Information communication craftman: 필기",
      "정보통신기사 =Information communication craftman: 과년도",
      "(윤성우의 열혈) C++ 프로그래밍",
      "(Do it!) 스위프트로 아이폰 앱 만들기: 입문",
      "(Do it!) 점프 투 파이썬 :전면개정판",
    ],
  },
  {
    major: "전자정보공학부 IT융합전공",
    grade: "18학번",
    bookList: [
      "신호 및 시스템",
      "선형대수학 express",
      "DSP First",
      "천일수학.1",
      "확률, 랜덤변수 및 랜덤신호 원리",
      "기초전자실험 :with PSpice",
      "DSP first",
      "이사야 벌린의 자유론",
      "Principles of communication :systems, modulation, and noise",
      "(윤성우의 열혈) C 프로그래밍",
    ],
  },
  {
    major: "전자정보공학부 IT융합전공",
    grade: "19학번",
    bookList: [
      "(컴퓨팅 사고력을 키우는) 이산수학",
      "(알기 쉬운)선형대수",
      "기초전자실험 :with PSpice",
      "Engineering electromagnetics",
      "(Android Studio를 활용한) 안드로이드 프로그래밍 :Android 10.0(Q) 지원, Android Studio 3.x 사용",
      "(세계 금융시장을 뒤흔든) 투자 아이디어",
      "열하일기",
      "러닝 파이썬",
      "파이썬 라이브러리를 활용한 데이터 분석",
      "(Hayt의) 전자기학",
    ],
  },
  {
    major: "전자정보공학부 IT융합전공",
    grade: "20학번",
    bookList: [
      "11문자 살인사건",
      "제3의 물결",
      "영혼을 위한 닭고기 수프",
      "(가장 쉬운) 스페인어 첫걸음의 모든 것 :회화편＋문법편",
      "참을 수 없는 존재의 가벼움",
      "호밀밭의 파수꾼",
      "러닝 파이썬",
    ],
  },
  {
    major: "전자정보공학부 IT융합전공",
    grade: "21학번",
    bookList: [
      "데미안",
      "정석 新 사전: 최신 바둑이론을 도입하여 바로 활용할 수 있는 정석사전!",
      "(고객지향적) 유통관리 =Marketing channel management",
      "위대한 개츠비",
      "실천적 불교사상",
      "三國志",
      "파이썬을 이용한 통계적 머신러닝",
      "(고객 지향적) 유통관리",
      "편지",
      "소크라테스의 변명 外",
    ],
  },

  {
    major: "전자정보공학부 전자공학전공",
    grade: "12학번",
    bookList: [
      "CMOS digital integrated circuits :analysis and design",
      "Digital design, with RTL design, VHDL, and Verilog",
      "디지털 신호처리:원리, 알고리즘, 응용",
      "디스플레이 공학.1,LCD",
      "(알기 쉬운)선형대수",
      "(파이썬으로 배우는) 알고리즘 트레이딩: 내 손으로 만드는 자동 주식 거래",
      "Beginning Linux programming",
      "디스플레이 공학개론 =Introduction to display engineering",
      "해킹:공격의 예술",
      "색 보정 룩북: 영화영상을 위한 크리에이티브 보정 기법",
    ],
  },

  {
    major: "전자정보공학부 전자공학전공",
    grade: "13학번",
    bookList: [
      "통신이론",
      "디지털 신호처리:원리, 알고리즘, 응용",
      "Semiconductor physics and devices :basic principles",
      "(21세기) 먼나라 이웃나라",
      "정보통신기사 :필기",
      "오픈스택을 다루는 기술 :실무에서 알아야 할 기술은 따로 있다!",
      "Advanced engineering mathematics",
      "코딩 인터뷰 완전 분석   :189가지 프로그래밍 문제와 해법",
      "전자기학",
      "(Visual C++을 이용한) 실용 영상 처리",
    ],
  },

  {
    major: "전자정보공학부 전자공학전공",
    grade: "14학번",
    bookList: [
      "전자기학",
      "미분적분학 =Calculus",
      "Advanced engineering mathematics",
      "통신이론",
      "CMOS digital integrated circuits :analysis and design",
      "Introduction to microelectronic fabrication",
      "Computer networking :a top-down approach",
      "전자기학 =Engineering electromagnetics",
      "무선설비기사 =Radiooperator :과년도",
      "무선설비기사 =Radio operator :필기",
    ],
  },

  {
    major: "전자정보공학부 전자공학전공",
    grade: "15학번",
    bookList: [
      "전자기학 =Engineering electromagnetics",
      "신호 및 시스템",
      "마이크로파 공학",
      "통신이론",
      "Introduction to microelectronic fabrication",
      "Semiconductor physics and devices :basic principles",
      "Microwave engineering",
      "기초 전자 회로 실험",
      "안테나 이론 :해석과 설계",
      "구토",
    ],
  },

  {
    major: "전자정보공학부 전자공학전공",
    grade: "16학번",
    bookList: [
      "전자기학 =Engineering electromagnetics",
      "(렛유인) 한권으로 끝내는 전공 면접 반도체",
      "Advanced engineering mathematics",
      "마이크로파 공학",
      "Semiconductor physics and devices :basic principles",
      "컴퓨터 구조 및 설계 :하드웨어/소프트웨어 인터페이스",
      "(최적합) ACA 포토샵CC =Adobe Certified Associate & Photoshop CC :국제인증 자격증",
      "일반물리학",
      "디지털 논리회로:이론, 실습, 시뮬레이션",
      "Radar systems analysis and design using MATLAB",
    ],
  },

  {
    major: "전자정보공학부 전자공학전공",
    grade: "17학번",
    bookList: [
      "아두이노 완전정복 :실험 KIT와 함께하는 ARDUINO 입문서",
      "(가장 쉬운) 스페인어 첫걸음의 모든 것 :회화편＋문법편",
      "이갈리아의 딸들",
      "CMOS VLSI 설계 원리",
      "DSP First",
      "디지털공학 =Digital engineering",
      "사자와 마녀와 옷장",
      "(리처드 포스터 ) 영적 훈련과 성장",
      "Introduction to linear algebra",
      "Signals & systems",
    ],
  },

  {
    major: "전자정보공학부 전자공학전공",
    grade: "18학번",
    bookList: [
      "고도를 기다리며",
      "전자기학 =Engineering electromagnetics",
      "신약성서는 오늘 우리에게 이렇게 증언한다:월요신학서당 편",
      "미분적분학 =Calculus",
      "라즈베리파이로 시작하는 핸드메이드 IoT :직접 체험하며 배우는 임베디드 IoT 프로그래밍",
      "선형대수학과 응용",
      "신호 및 시스템",
      "대학물리학 9판 해설집",
      "(Do it!) 점프 투 파이썬 :전면개정판",
      "통신이론",
    ],
  },

  {
    major: "전자정보공학부 전자공학전공",
    grade: "19학번",
    bookList: [
      "데이터통신 길라잡이 =Data communication",
      "(이기적) 정보처리기능사 :필기 기본서",
      "유럽 5개국 :영국·프랑스·스위스·이탈리아·스페인 :2018~2019년 최신개정판",
      "RF microelectronics",
      "Signals and systems using MATLAB",
      "전기.전자공학개론",
      "역사란 무엇인가:[역사란 현재와 과거의 끊임없는 대화]",
      "기초전자기학",
      "통신이론",
      "Introduction to Linear Algebra",
    ],
  },

  {
    major: "전자정보공학부 전자공학전공",
    grade: "20학번",
    bookList: [
      "C언어 기초 :C언어를 이용한 SW코딩입문서",
      "(재미삼아) 아두이노 =Arduino",
      "(Hackers) TOEFL writing :intermediate",
      "(Hackers) TOEFL speaking: intermediate",
      "(Do it!) 안드로이드 앱 프로그래밍",
      "(Hackers) TOEFL listening: intermediate",
      "(Hackers) TOEFL reading: intermediate",
      "(윤성우의 열혈) TCP/IP 소켓 프로그래밍",
    ],
  },

  {
    major: "전자정보공학부 전자공학전공",
    grade: "21학번",
    bookList: [
      "미분적분학 =Calculus",
      "(핵심) 일반화학",
      "왜 나는 너를 사랑하는가",
      "역사란 무엇인가",
      "이기적 유전자 :진화론의 새로운 패러다임",
    ],
  },

  {
    major: "정보사회학과",
    grade: "12학번",
    bookList: [
      "직무별 취업비법서 :국내 최초 현직자가 전하는",
      "(Dear) 유통관리사 2급 :테마별 기출족보 총정리",
      "性의 역사",
      "사회조사분석사+α :2급필기 사회과학 조사방법론.2015",
      "(Union) PSAT 원리와 기술 :상황판단",
      "(2017) 수능기출 사회 Best 100",
      "민준호 사회 진도별 모의고사 :나의 응답",
      "경영전략",
      "내 영혼이 따뜻했던 날들",
      "육일약국 갑시다",
    ],
  },
  {
    major: "정보사회학과",
    grade: "13학번",
    bookList: [
      "The law and policy of the World Trade Organization :text, cases, and materials",
      "(新) 국제경제법 =International economic law",
      "Social network analysis :a handbook",
      "세법강의",
      "거시경제론",
      "나는 나를 파괴할 권리가 있다 :김영하 장편소설",
      "(No plan! no problem!) Enjoy 푸껫",
      "종합물류의 이해",
      "총, 균, 쇠 :무기, 병균, 금속은 인류의 운명을 어떻게 바꿨는가",
      "글로벌경영",
    ],
  },
  {
    major: "정보사회학과",
    grade: "14학번",
    bookList: [
      "(SPSS) 사회조사분석사 :2급 2차 실기",
      "사이버범죄학 =Cyber criminology :원인/유형/대책",
      "영단기 新토익 :RC",
      "Mr.뱅의 금융상식 :인사담당자가 공개하는 금융상식 필독서",
      "해커스 新 토익 보카 =Vocabulary",
      "(친절한) 재무회계 =A gentle introduction to Introduce financial accounting",
      "Essentials of management information systems",
      "아내를 모자로 착각한 남자",
      "계량경제학강의 =Lectures on econometrics",
      "Understanding modern warfare",
    ],
  },
  {
    major: "정보사회학과",
    grade: "15학번",
    bookList: [
      "사이버범죄학 =Cyber criminology :원인/유형/대책",
      "이갈리아의 딸들",
      "커뮤니케이션 이론",
      "사회조사 분석사 2급    :2차 실기    :한권으로 끝내기",
      "국가란 무엇인가",
      "(한끝 clear) 사회조사분석사 :2급 필기 :한권으로 끝내기",
      "사회조사분석사 +α :2급 실기 필답형(논술형)",
      "진로 탐색 및 직업 선택 :NCS 직업기초능력의 이해와 실습",
      "해리포터 시리즈",
      "추상표현주의",
    ],
  },
  {
    major: "정보사회학과",
    grade: "16학번",
    bookList: [
      "사이버범죄학 =Cyber criminology :원인/유형/대책",
      "사회조사분석사 :2급 필기 :한권으로 올인하기",
      "사회조사방법론:SPSS WIN 통계분석",
      "SPSS를 활용한 사회조사분석",
      "(현대) 사회학 이론과 그 고전적 뿌리",
      "(2019 NCS 기반 믿고보는 사경환) 사회조사분석사 2급 2차 실기 필답형(서술형) 사이다 V8",
      "글로벌 무역학개론",
      "정보사회이론",
      "하나님을 아는 지식",
      "(꼼꼼한) 아마존 셀러 가이드북: 아마존 셀러가 알아야 할 A to Z",
    ],
  },
  {
    major: "정보사회학과",
    grade: "17학번",
    bookList: [
      "사이버범죄학 =Cyber criminology :원인/유형/대책",
      "정보사회이론",
      "멋진 신세계",
      "국가란 무엇인가",
      "비전공자를 위한 R 입문서: R로 만드는 워드 클라우드",
      "JLPT 한권으로 끝내기 보카",
      "수리통계학",
      "(NCS 기반 믿고보는 사경환) 사회조사분석사 2급 2차 실기 필답형(서술형) 사이다 V7",
      "해리포터와 마법사의 돌",
      "철학 개론",
    ],
  },
  {
    major: "정보사회학과",
    grade: "18학번",
    bookList: [
      "사이버범죄학 =Cyber criminology :원인/유형/대책",
      "이기적 유전자",
      "멋진 신세계",
      "사회조사 분석사 2급    :2차 실기    :한권으로 끝내기",
      "이기적 유전자 :진화론의 새로운 패러다임",
      "군주론",
      "사회문제론 :이론, 실태, 지구적 시각",
      "국가란 무엇인가",
      "총, 균, 쇠 :무기, 병균, 금속은 인류의 운명을 어떻게 바꿨는가",
      "사회사상사",
    ],
  },
  {
    major: "정보사회학과",
    grade: "19학번",
    bookList: [
      "청춘의 독서 :세상을 바꾼 위험하고 위대한 생각들",
      "사이버범죄학 =Cyber criminology :원인/유형/대책",
      "학교를 넘어서",
      "(방법서설·성찰) 데카르트 연구",
      "사회학적 상상력",
      "사회학: 비판적 사회읽기",
      "현대사회학 =Sociology",
      "향연",
      "부동산학개론",
      "개념어 사전:인터넷에서도 검색할 수 없는 생생한 지식의 보물 창고",
    ],
  },
  {
    major: "정보사회학과",
    grade: "20학번",
    bookList: [
      "사회조사방법론",
      "자유론",
      "사회사상사",
      "오리엔트 특급 살인",
      "1984",
      "역사란 무엇인가",
      "(21세기) 먼나라 이웃나라",
      "(R을 활용한)사회네트워크분석 입문",
      "대학생을 위한 활용 독일어 =Lebendiges Deutsch fur studenten.1",
      "(新) 국제경제법 =International economic law :전면개정판",
    ],
  },
  {
    major: "정보사회학과",
    grade: "21학번",
    bookList: [
      "자본주의 :어디서 와서 어디로 가는가",
      "사회학: 비판적 사회읽기",
      "Unlock.[Level] 3 :listening, speaking ＆ critical thinking : student's book",
      "죄와 벌:표도르 마하일로비치 도스또예프스끼 장편소설",
      "사회학의 핵심 개념들 :개정증보판",
    ],
  },

  {
    major: "정보통계·보험수리학과",
    grade: "12학번",
    bookList: [
      "미시경제학",
      "수리통계학",
      "보험 상식사전",
      "(한권으로 끝내는) 손해사정이론 보험업법 :손해사정사 및 보험계리사 1차 시험 대비",
      "(2019) 고종훈 한국사 기출 엄선 400제: 2017~2019년 기출문제",
      "L-TAB 롯데그룹 인·적성검사 :인문계 :종합편",
      "Probability and Statistical Inference",
      "Loss models :from data to decisions",
      "(박금우) 이공개 수학: 단기 합격자의 공부법을 담은 기본서",
      "보험조사분석사   :문제로끝내기   :통합문제집 Part 1+2",
    ],
  },

  {
    major: "정보통계·보험수리학과",
    grade: "13학번",
    bookList: [
      "수리통계학 =Mathematical statistics",
      "몽테뉴 수상록",
      "(SOA exam FM) 금융수리",
      "데이터분석 준전문가 :ADsP 新 2017 :30일 간의 데이터 분석 여행!",
      "리스크와 보험 =Risk & Insurance",
      "(친절한) 재무회계 =A gentle introduction to Introduce financial accounting",
      "(SPSS) 사회조사분석사 :2급 2차 실기",
      "공무원 최빈출 어휘 3000+ :기본어휘1500",
      "Introduction to mathematical statistics",
      "Introduction to probability models",
    ],
  },

  {
    major: "정보통계·보험수리학과",
    grade: "14학번",
    bookList: [
      "(2018) 보험수학 perfect 정리 :보험계리사 1차시험 대비",
      "범주형 자료분석 개론",
      "(2017) 일반수학 및 확률통계 :보험계리사 1차시험 대비",
      "(2018) 보험수리학 Perfect 정리: 보험계리사 2차시험 대비",
      "SAS data step",
      "(2017) 보험수학 perfect 정리",
      "수리통계학",
      "리스크와 보험 =Risk & Insurance",
      "(2017) 계리리스크관리 :보험계리사 2차시험 대비",
      "Linear algebra and its applications",
    ],
  },

  {
    major: "정보통계·보험수리학과",
    grade: "15학번",
    bookList: [
      "Elementary survey sampling",
      "표본조사의 이해와 활용",
      "보험수리학 = Actuarial mathematics",
      "계리 모형론 =Actuarial model theory",
      "Mathematical statistics with applications",
      "통계적 품질관리",
      "Loss models :from data to decisions",
      "수리통계학",
      "IFRS 중급회계",
      "데이터 분석 전문가 가이드 :데이터 분석 자격검정 공식수험서 =The guide for advanced data analytics professional",
    ],
  },

  {
    major: "정보통계·보험수리학과",
    grade: "16학번",
    bookList: [
      "Applied multivariate statistical analysis",
      "수리통계학",
      "(SOA exam FM) 금융수리",
      "최신보험수리학",
      "IFRS 중급 회계 =International financial reporting standards intermediate accounting",
      "범주형 자료분석 개론",
      "회귀분석",
      "(시사와 함께하는) 거시경제학",
      "(예제를 통한) 회귀분석",
      "Introduction to probability models",
    ],
  },

  {
    major: "정보통계·보험수리학과",
    grade: "17학번",
    bookList: [
      "수리통계학",
      "(2018) 보험수학 perfect 정리 :보험계리사 1차시험 대비",
      "표본조사의 이해와 활용",
      "(SOA exam FM) 금융수리",
      "(2017) 보험수학 perfect 정리",
      "통계학을 위한 선형대수",
      "회귀분석",
      "최신보험수리학",
      "통계적 품질관리",
      "(친절한) 재무회계=Financial accounting",
    ],
  },

  {
    major: "정보통계·보험수리학과",
    grade: "18학번",
    bookList: [
      "보험수리학 = Actuarial mathematics",
      "Loss models :from data to decisions",
      "회귀분석",
      "수리통계학",
      "Loss models, student solutions manual :from data to decisions",
      "Applied multivariate statistical analysis",
      "표본조사의 이해와 활용",
      "회귀분석 :기초와 응용",
      "(Excel, Spss, R로 배우는) 통계학 입문 =Introduction to statistics",
      "최신보험수리학",
    ],
  },

  {
    major: "정보통계·보험수리학과",
    grade: "19학번",
    bookList: [
      "통계학을 위한 선형대수",
      "SAS 시스템과 SAS 언어=(The) SAS system for Windows version 8",
      "통계적 품질관리",
      "범주형 자료분석 개론:SAS의 응용 및 해석",
      "코스모스",
      "(Enjoy) 오사카 :교토·고베·나라",
      "(친절한) 재무회계 =Financial accounting",
      "해커스 new 텝스 :listening",
      "소유냐 존재냐",
      "경제학 연습 :거시편",
    ],
  },

  {
    major: "정보통계·보험수리학과",
    grade: "20학번",
    bookList: [
      "수리통계학",
      "리스크와 보험 =Risk & Insurance",
      "(선택과 집중의) 다이제스트 경제학",
      "사랑은 하지 않고 있습니다",
      "Corporate finance :core principles ＆ applications",
      "(Do it!) 점프 투 파이썬 :전면개정판",
      "리스크와 보험 =Risk ＆ insurance",
      "멋진 신세계",
      "통계적 품질관리",
      "핸즈온 머신러닝",
    ],
  },

  {
    major: "정보통계·보험수리학과",
    grade: "21학번",
    bookList: [
      "올 댓 매너 =All that manner :비즈니스매너, 공공생활매너, 글로벌매너",
      "올 댓 매너 =All that manner :글로벌매너, 비즈니스매너, 공공생활매너",
    ],
  },

  {
    major: "정보통신전자공학부",
    grade: "12학번",
    bookList: [
      "SK 그룹 SKCT :SK종합역량검사 :실전모의고사",
      "전자기학",
      "총, 균, 쇠 :무기, 병균, 금속은 인류의 운명을 어떻게 바꿨는가",
      "(우영이와 함께하는) 무선공학 통신공학 통신이론 :공통이론",
      "(이렇게 기막힌 적중률 2017) 정보처리기사 :필기 기본서",
      "(2주 만에 끝내는)해커스 토익 Speaking Start",
      "정보 보안 개론 :한 권으로 배우는 보안 이론의 모든 것",
      "사랑의 온도 :하명희 장편소설",
      "Schaum's outline of theory and problems of set theory and related topics",
      "(Hackers) 해커스 텝스 최신기출유형 실전 1200제",
    ],
  },

  {
    major: "정보통신전자공학부",
    grade: "13학번",
    bookList: [
      "Computer networking :a top-down approach",
      "인터넷 이해와 활용 :인터넷 기초부터 홈페이지 제작실습까지",
      "정보 보안 개론 :한 권으로 배우는 보안 이론의 모든 것",
      "무선설비기사 =Radio operator :과년도",
      "(최적합) 네트워크관리사 1·2급 필기 =Network Administrator :최고의 적중률로 합격을 보장하는 국가공인 2017년 최신 기출문제 수록",
      "Principles of communication :systems, modulation, and noise",
      "삼성 소프트웨어 역량테스트 :삼성그룹 소프트웨어직군 공채 실전대비서",
      "데미안",
      "국가란 무엇인가",
      "인도 오지 기행:어머니의 품, 산들의 고향에 가다",
    ],
  },

  {
    major: "정보통신전자공학부",
    grade: "14학번",
    bookList: [
      "Eagle CAD 배우기",
      "아리랑 :趙廷來 大河小說",
      "Introduction to analog and digital communications",
      "무궁화 꽃이 피었습니다 :김진명 장편소설",
      "데이터분석 전문가 준전문가 :단기완성",
      "(MongoDB master가 해설하는) NoSQL & mongoDB",
      "(김성천 강사의) PADS로 PCB 아트웍 혼자하기",
      "전자기학",
      "파리대왕",
      "(new)외국계 기업 취업전략:헤드헌터가 공개하는 입사 노하우",
    ],
  },

  {
    major: "정치외교학과",
    grade: "12학번",
    bookList: [
      "국제정세의 이해 :위기의 시대, 지구촌의 어젠다와 국제관계 =Understanding international relations : issues in global village in the age of crisis",
      "역사란 무엇인가",
      "(All in one) 이유정 지텔프 :level 2 문법편",
      "왜 나는 너를 사랑하는가",
      "해커스 토익 실전 1000제 :reading :해설집.1",
      "아공법 3.0 :문제집 중심의 공무원시험 공부법",
      "(2018) 재무회계 기출 best 문제 :공인회계사·세무사 1차 시험대비",
      "군주론",
      "국부론",
      "죽은 경제학자의 살아있는 아이디어",
    ],
  },
  {
    major: "정치외교학과",
    grade: "13학번",
    bookList: [
      "군주론",
      "털없는 원숭이:동물학적 인간론",
      "(2019) 고종훈 한국사 기출 엄선 400제: 2017~2019년 기출문제",
      "내 영혼이 따뜻했던 날들",
      "(2019 김덕관 강한 행정학) 기출에 강한 행정학",
      "신경수 통합 객관식 경제학 기출문제집: 미시·거시·국제",
      "(윤우혁) 헌법 기출문제집",
      "국제개발협력 :더불어 사는 세상을 위한 소중한 첫걸음.입문편",
      "오디세이아 :트로이 전쟁, 그 후 10년의 이야기",
      "국가란 무엇인가",
    ],
  },
  {
    major: "정치외교학과",
    grade: "14학번",
    bookList: [
      "현대 정당정치의 이해",
      "이지 유럽",
      "債權各論",
      "헌법의 풍경:잃어버린 헌법을 위한 변론",
      "역사란 무엇인가",
      "제도분석 :이론과 쟁점",
      "(처음 읽는) 러시아 역사",
      "(셀프트래블) 스위스 =Switzerland",
      "아름다운 그늘:신경숙 산문집",
      "(시사와 함께하는) 거시경제학s",
    ],
  },
  {
    major: "정치외교학과",
    grade: "15학번",
    bookList: [
      "침묵",
      "역사란 무엇인가",
      "제도분석 :이론과 쟁점",
      "국제개발협력 :더불어 사는 세상을 위한 소중한 첫걸음.심화편",
      "해상보험=Marine insurance",
      "감시와 처벌:감옥의 역사",
      "(사회과학도를 위한)중국학 강의",
      "나는 나를 파괴할 권리가 있다 :김영하 장편소설",
      "(친절한) 재무회계 =A gentle introduction to Introduce financial accounting",
      "Global capitalism :its fall and rise in the twentieth century",
    ],
  },
  {
    major: "정치외교학과",
    grade: "16학번",
    bookList: [
      "침묵",
      "국제개발협력 :더불어 사는 세상을 위한 소중한 첫걸음.심화편",
      "철학과 굴뚝청소부:데카르트에서 들뢰즈까지 : 근대철학의 경계들",
      "정치학 :인간과 사회 그리고 정치",
      "생산운영관리 =Operations management",
      "관자",
      "Essence of decision :explaining the Cuban Missile Crisis",
      "이갈리아의 딸들",
      "변환의 세계정치 =Transformation of world politics",
      "열린사회와 그 적들",
    ],
  },
  {
    major: "정치외교학과",
    grade: "17학번",
    bookList: [
      "죽은 경제학자의 살아있는 아이디어",
      "역사란 무엇인가",
      "유한계급론",
      "현대 외교정책론 =Foreign policy in the 21st century",
      "프로테스탄티즘의 윤리와 자본주의 정신",
      "소크라테스의 변명:크리톤·파이돈·향연",
      "(현대) 외교 정책론",
      "국부론",
      "사회계약론",
      "국가란 무엇인가",
    ],
  },
  {
    major: "정치외교학과",
    grade: "18학번",
    bookList: [
      "역사란 무엇인가",
      "침묵",
      "감시와 처벌:감옥의 역사",
      "참을 수 없는 존재의 가벼움",
      "죽은 경제학자의 살아있는 아이디어",
      "일차원적 인간 :선진산업사회의 이데올로기 연구",
      "자유론",
      "해방전후사의 인식.1 - 6",
      "한국정치론 =Understanding Korean politics",
      "아리랑",
    ],
  },
  {
    major: "정치외교학과",
    grade: "19학번",
    bookList: [
      "한국정치론 =Understanding Korean politics",
      "미국헌법과 민주주의",
      "국제관계학   :인간과 세계 그리고 정치",
      "침묵",
      "역사란 무엇인가",
      "무역상무",
      "지구 속 여행",
      "시편 주석",
      "주식투자 무작정 따라하기",
      "국화와 칼: 일본 문화의 틀",
    ],
  },
  {
    major: "정치외교학과",
    grade: "20학번",
    bookList: [
      "역사란 무엇인가",
      "데미안",
      "그레이스",
      "현대무기체계론",
      "시녀 이야기",
      "(새로 만든) 먼나라 이웃나라",
      "(글로벌 시대의) 경영학 =Principles of management in global era",
      "글로벌 무역학개론",
      "국제관계학   :인간과 세계 그리고 정치",
      "순수이성비판",
    ],
  },
  {
    major: "정치외교학과",
    grade: "21학번",
    bookList: [
      "문명의 충돌 :세계질서 재편의 핵심 변수는 무엇인가",
      "역사란 무엇인가",
      "아마데우스",
      "시간을 파는 상점 :김선영 장편소설",
      "(인조이) 뉴욕      :워싱턴D.C.·보스턴·나이아가라 폭포",
      "(새로운 패러다임의) 비교정치 =New paradigm on comparative politics",
    ],
  },
  {
    major: "중어중문학과",
    grade: "12학번",
    bookList: [
      "(2019 선재국어) 기출실록",
      "(쉽게 알고 배우는) 易知 한자 :상공회의소 2급 최종모의고사",
      "(전한길 한국사) 7.0: 주제별 최종점검",
      "國王 국어 포켓북",
      "사람의 아들:이문열 장편소설",
      "황태자의 마지막 키스",
      "(2019) 민준호 사회: 진도별·동형 모의고사",
      "이동기 영어 약점체크 모의고사",
      "(객관식 다이어트) 경제학 :미시편",
      "(Pass) 전산세무 1급 :필기 실기",
    ],
  },
  {
    major: "중어중문학과",
    grade: "13학번",
    bookList: [
      "중국문학사",
      "맨큐의 경제학 6판 :연습문제풀이",
      "(왜?라는 질문에 속시원히 대답해 주는) 중국어문법책",
      "무역영어 :1급 :4개년 기출문제집 :관세사·국제무역사·무역영어 동시대비",
      "(Excel) 경영과학 =Management science",
      "(왜? 라는 질문에 속시원히 답해주는) 중국어 문법책",
      "신공략 중국어:기초편",
      "(워런 버핏의) 주식투자 콘서트 :encore ver. 2018",
      "국가란 무엇인가",
      "신공략 중국어:프리토킹편",
    ],
  },
  {
    major: "중어중문학과",
    grade: "14학번",
    bookList: [
      "(스펙에 通하다!) 상공회의소 漢字 고급 1·2 :최종모의고사",
      "(왜? 라는 질문에 속시원히 답해주는) 중국어 문법책",
      "(쉽게 알고 배우는) 易知 한자 :상공회의소 2급 기본서",
      "(쉽게 알고 배우는) 상공회의소 易知 한자 :2급",
      "(hoa:) 재경관리사 한권으로 끝내기",
      "참을 수 없는 존재의 가벼움",
      "Essentials of corporate finance",
      "두보 시선",
      "왜 나는 너를 사랑하는가",
      "(쉽게 알고 배우는) 易知 한자 :상공회의소 2급 최종모의고사",
    ],
  },
  {
    major: "중어중문학과",
    grade: "15학번",
    bookList: [
      "역사란 무엇인가",
      "논어",
      "중국문학사",
      "미시경제학 :수학노트와 연습문제 해답",
      "(왜? 라는 질문에 속시원히 답해주는) 중국어 문법책",
      "중국소설사의 이해",
      "국가론",
      "고문진보 =Guwen Zhembao",
      "홍콩 마카오 =Hongkong｜Macau :2018-2019 최신판",
      "관세법 =Customs Law: 2018년 개정판",
    ],
  },
  {
    major: "중어중문학과",
    grade: "16학번",
    bookList: [
      "(왜? 라는 질문에 속시원히 답해주는) 중국어 문법책",
      "논어",
      "(단기간에 끝나는) 오! 관세법 요약집",
      "공자의 생애와 사상",
      "화폐와 금융시장",
      "거시경제학 =Macro economics :연습문제 풀이·해답과 국가고시기출문제 및 풀이",
      "스페인어 문법=Gramatica Espanola",
      "낯선 곳에서 나를 만나다",
      "중국의 도시 노동시장과 사회:상하이시 사례를 중심으로",
      "11문자 살인사건",
    ],
  },
  {
    major: "중어중문학과",
    grade: "17학번",
    bookList: [
      "시를 잊은 그대에게",
      "몰입의 즐거움",
      "회계기초 탈출기 15일 플랜!     :회계사 아빠와 왕초보 딸의 재밌는 회계 수다",
      "해상보험",
      "(쉽게 알고 배우는) 易知 한자 :상공회의소 2급 기본서",
      "(21세기) 먼나라 이웃나라",
      "빙점",
      "짧은 이야기, 긴 생각 :이어령 80초 생각 나누기",
      "파우스트",
      "(新譯)陶淵明(도연명)",
    ],
  },
  {
    major: "중어중문학과",
    grade: "18학번",
    bookList: [
      "한자능력 검정시험:2급",
      "냉정과 열정 사이 :rosso",
      "총, 균, 쇠: 무기, 병균, 금속은 인류의 운명을 어떻게 바꿨는가",
      "공자의 생애와 사상",
      "국제운송물류=International transportation & logistics",
      "우리는 사랑일까 :알랭 드 보통 장편소설",
      "(Updated) 일하면서 밥해먹기",
      "화성에서 온 남자 금성에서 온 여자",
      "열하일기",
      "Negotiation: readings, exercises and cases",
    ],
  },
  {
    major: "중어중문학과",
    grade: "19학번",
    bookList: [
      "(왜? 라는 질문에 속시원히 답해주는) 중국어 문법책",
      "셰익스피어 4대 비극",
      "(New 2007년판) 형법전",
      "거시경제학 =Macroeconomics",
      "사회조사방법론",
      "반 고흐, 영혼의 편지",
      "(New) 청춘, 내일로 :내일로 기차여행 책임가이드",
      "Divergent",
      "(처음 읽는) 서양철학사 :서양의 대표 철학자 40인과 시작하는 철학의 첫걸음",
      "허삼관 매혈기 :위화 장편소설",
    ],
  },
  {
    major: "중어중문학과",
    grade: "20학번",
    bookList: ["(新譯) 屈原", "산해경 : 동양 최고의 기서"],
  },
  {
    major: "중어중문학과",
    grade: "21학번",
    bookList: [
      "웃는 남자",
      "데미안",
      "사랑은 상처를 허락하는 것이다: anthorogy",
      "(장편소설) 백성의 신 황희",
    ],
  },

  {
    major: "철학과",
    grade: "12학번",
    bookList: [
      "정신현상학",
      "국가",
      "(플라톤의) 국가(正體)",
      "동물 해방",
      "죽음에 이르는 병",
      "비극의 탄생/즐거운 지식",
      "한국철학사상사",
      "소유인가 존재인가",
      "임마누엘 칸트",
      "사랑의 기술",
    ],
  },
  {
    major: "철학과",
    grade: "13학번",
    bookList: [
      "인간의 조건",
      "한국철학사상사",
      "(플라톤의) 국가(正體)",
      "국가",
      "파리대왕",
      "상실의 시대",
      "이사야 벌린의 자유론",
      "파리 대왕",
      "차트의 기술 :한 권으로 끝내는 기술적 분석의 모든 것",
      "아내를 모자로 착각한 남자",
    ],
  },
  {
    major: "철학과",
    grade: "14학번",
    bookList: [
      "임마누엘 칸트",
      "인간의 조건",
      "한국철학사상사",
      "현대 인식론",
      "(시대와의 대화) 칸트와 헤겔의 철학",
      "리바이어던",
      "자본론:정치경제학 비판",
      "칸트철학 입문",
      "(윤성우의 열혈) C++ 프로그래밍",
      "공리주의 =Utilitarianism",
    ],
  },
  {
    major: "철학과",
    grade: "15학번",
    bookList: [
      "중국철학사",
      "(퍼펙트) 무역영어 1급 =Perfect guide to trade English :이론 + 기출문제 :무역영어 2급 동시 대비",
      "인도철학사",
      "논리와 사고",
      "뇌는 윤리적인가 :뇌과학으로 푸는 인간 본성과 생명윤리의 딜레마",
      "정체성",
      "도덕경",
      "(플라톤의) 국가(正體)",
      "한국철학사상사",
      "도의 논쟁자들 :중국 고대 철학 논쟁",
    ],
  },
  {
    major: "철학과",
    grade: "16학번",
    bookList: [
      "중국철학사",
      "현대 인식론",
      "인식론의 역사",
      "도덕 형이상학을 위한 기초 놓기",
      "죽음의 철학",
      "傳習錄:실천적 삶을 위한 지침",
      "감시와 처벌:감옥의 역사",
      "한국철학사상사",
      "일리아스 =Ilias of Homeros",
      "장미의 이름 작가 노트",
    ],
  },
  {
    major: "철학과",
    grade: "17학번",
    bookList: [
      "감시와 처벌:감옥의 역사",
      "대학·중용",
      "사랑의 기술",
      "(플라톤의) 국가(正體)",
      "이방인",
      "중국철학사",
      "구토",
      "Athenaze :an introduction to ancient Greek",
      "중용",
      "한국철학사상사",
    ],
  },
  {
    major: "철학과",
    grade: "18학번",
    bookList: [
      "국가",
      "대학·중용",
      "중국철학사",
      "프로타고라스",
      "반 고흐, 영혼의 편지",
      "고대철학에서 중세철학까지",
      "감시와 처벌:감옥의 역사",
      "(플라톤의) 국가(正體)",
      "철학의 위안",
      "논어",
    ],
  },
  {
    major: "철학과",
    grade: "19학번",
    bookList: [
      "인식론의 역사",
      "(비판적 사고를 위한) 논리=Logic for critical thinking",
      "니코마코스 윤리학",
      "철학 개론",
      "중국철학사",
      "위대한 개츠비",
      "숲속의 방",
      "(플라톤의) 국가(正體)",
      "라루스 서양미술사",
      "(역사와 문화, 이야기로 즐기는) 와인 상식사전 =Common sense dictionary for wine",
    ],
  },
  {
    major: "철학과",
    grade: "20학번",
    bookList: [
      "(성 어거스틴의) 고백록",
      "니코마코스 윤리학",
      "시간론",
      "피셔의 비판적 사고",
      "수학의 정석:기본편",
      "Elementary logic",
      "예루살렘의 아이히만",
      "구토",
      "The elements of moral philosophy",
      "국제관계학   :인간과 세계 그리고 정치",
    ],
  },
  {
    major: "철학과",
    grade: "21학번",
    bookList: [
      "철학의 주요문제에 대한 논쟁",
      "구토",
      "이갈리아의 딸들",
      "맹자",
      "인간이란 무엇인가",
      "지구 살림, 철학에게 길을 묻다 :지구 살림의 길, 철학이 답하다",
      "칸트철학 입문",
      "칼의 노래",
      "새로운 인생",
      "정신현상학",
    ],
  },

  {
    major: "컴퓨터학부",
    grade: "12학번",
    bookList: [
      "C로 배우는 쉬운 자료구조",
      "(Do it!) HTML5+CSS3 웹 표준의 정석",
      "(Do it!) Node.js 프로그래밍 :실제 서버로 구동 가능한 코드로 배운다!",
      "(모던 웹을 위한) JavaScript jQuery 입문",
      "코딩 인터뷰 완전 분석   :189가지 프로그래밍 문제와 해법",
      "주식투자 무작정 따라하기",
      "System software :an introduction to systems programming",
      "글로벌 무역학개론",
      "(모던 웹을 위한) Node.js 프로그래밍",
      "GoF의 디자인 패턴 :재사용성을 지닌 객체지향 소프트웨어의 핵심 요소",
    ],
  },
  {
    major: "컴퓨터학부",
    grade: "13학번",
    bookList: [
      "(NASM을 사용한) PC 어셈블러 프로그래밍",
      "(윤성우의 열혈) C++ 프로그래밍",
      "Operating system concepts :international student version",
      "(Do it!) Node.js 프로그래밍 :실제 서버로 구동 가능한 코드로 배운다!",
      "코딩 인터뷰 완전 분석   :189가지 프로그래밍 문제와 해법",
      "미분적분학 =Calculus",
      "(명품) Java programming",
      "(이렇게 기막힌 적중률 2017) 정보처리기사 :필기 기본서",
      "(모던 웹을 위한) Node.js 프로그래밍",
      "(후니의 쉽게 쓴) 시스코 네트워킹",
    ],
  },
  {
    major: "컴퓨터학부",
    grade: "14학번",
    bookList: [
      "(윤성우의 열혈) TCP/IP 소켓 프로그래밍",
      "(2017) 정보처리기사 :실기(산업기사 포함) 기본서",
      "(Do it!) Node.js 프로그래밍 :실제 서버로 구동 가능한 코드로 배운다!",
      "유닉스 리눅스 프로그래밍 필수 유틸리티:vim, make, gcc, gdb, svn, binutils",
      "리눅스 커널 내부구조 :리눅스 해커를 위한 지침서",
      "리눅스 시스템 프로그래밍",
      "(명품) Java programming",
      "(윤성우의 열혈) C++ 프로그래밍",
      "Operating system concepts :international student version",
      "(Do it!) 안드로이드 앱 프로그래밍 :안드로이드 7.0 누가 버전·안드로이드 스튜디오 반영판!",
    ],
  },
  {
    major: "컴퓨터학부",
    grade: "15학번",
    bookList: [
      "Concepts of programming languages",
      "(Do it!) Node.js 프로그래밍 :실제 서버로 구동 가능한 코드로 배운다!",
      "(Do it!) 안드로이드 앱 프로그래밍 :안드로이드 7.0 누가 버전·안드로이드 스튜디오 반영판!",
      "(SKCT) SK그룹 종합역량검사 :종합편",
      "(해커스) CJ 종합적성검사 CAT·CJAT",
      "(The) art of computer programming=컴퓨터 프로그래밍의 예술",
      "(프렌즈) 독일 =Germany",
      "성공과 실패를 결정하는 1%의 네트워크 원리",
      "(OpenGL을 이용한) 컴퓨터 그래픽스",
      "(알기 쉬운)선형대수",
    ],
  },
  {
    major: "컴퓨터학부",
    grade: "16학번",
    bookList: [
      "Node.js 교과서 =Node.js textbook :기본기에 충실한 노드제이에스 14 입문서",
      "Contemporary logic design",
      "Concepts of programming languages",
      "Java의 정석",
      "쉽게 배우는 알고리즘: 관계 중심의 사고법",
      "데미안",
      "과학혁명의 구조",
      "Data structures & other objects using Java :using J2SE 7.0",
      "Foundations of algorithms",
      "Introduction to linear algebra",
    ],
  },
  {
    major: "컴퓨터학부",
    grade: "17학번",
    bookList: [
      "(Rosen의) 이산수학",
      "Introduction to the theory of computation",
      "사랑의 기술",
      "컴퓨터 네트워킹:하향식 접근",
      "범인 없는 살인의 밤",
      "(교육학적 사유를 여는) 교육의 철학과 역사=Philosophy and history of education",
      "(C언어로 쉽게 풀어쓴) 자료 구조",
      "(윤성우의 열혈) C++ 프로그래밍",
      "주식시장의 보물찾기 :합병·기업분할·구조조정·유상증자",
      "안드로이드 앱 프로그래밍 :T아카데미의 명강의를 한 권에 담았다!",
    ],
  },
  {
    major: "컴퓨터학부",
    grade: "18학번",
    bookList: [
      "(명품) Java programming",
      "Data structures & other objects using Java :using J2SE 7.0",
      "(윤성우의 열혈) C++ 프로그래밍",
      "파우스트",
      "Java의 정석",
      "신약성서는 오늘 우리에게 이렇게 증언한다:월요신학서당 편",
      "(명품) JAVA programming",
      "총, 균, 쇠 :무기, 병균, 금속은 인류의 운명을 어떻게 바꿨는가",
      "Contemporary logic design",
      "(Do it!) Node.js 프로그래밍 :실제 서버로 구동 가능한 코드로 배운다!",
    ],
  },
  {
    major: "컴퓨터학부",
    grade: "19학번",
    bookList: [
      "(Rosen의) 이산수학",
      "(명품) Java programming",
      "(Do it!) 안드로이드 앱 프로그래밍",
      "(Android Studio를 활용한) 안드로이드 프로그래밍: Android 9.0(파이) 지원, Android Studio 3.x 사용",
      "Concepts of programming languages",
      "Introduction to the theory of computation",
      "(윤성우의 열혈) C++ 프로그래밍",
      "Java의 정석",
      "실용주의 프로그래머",
      "(풍부한 그림과 사진으로 배우는) 네트워크(Network) 쉽게, 더 쉽게",
    ],
  },
  {
    major: "컴퓨터학부",
    grade: "20학번",
    bookList: [
      "(명품) Java programming",
      "역사란 무엇인가",
      "Data structures & other objects using Java :using J2SE 7.0",
      "보카 바이블 4.0",
      "(윤성우의 열혈) C 프로그래밍",
      "(Do it!) 스위프트로 아이폰 앱 만들기: 입문",
      "JavaScript :the definitive guide : master the world's most-used programming language",
      "The design of everyday things",
      "Node.js, MongoDB와 Angular를 이용한 웹 개발: 웹 개발자들이 반드시 알아야 할 웹 개발 필수 학습서",
      "안드로이드 with Kotlin 앱 프로그래밍 가이드 :자바＋코틀린으로 만드는 APP 개발 필독서",
    ],
  },
  {
    major: "컴퓨터학부",
    grade: "21학번",
    bookList: [
      "역사란 무엇인가",
      "(Do it!) HTML5+CSS3 웹 표준의 정석",
      "(Rosen의) 이산수학",
      "(고객지향적) 유통관리 =Marketing channel management",
      "IFRS 회계원리=International financial reporting standards accounting principles",
      "(대한민국 여행자를 위한,) 제주도 여행백서",
      "왜 나는 너를 사랑하는가",
      "통계학의 이해 :excel 실습 =Introduction to statistics",
      "Effective C# :강력한 C# 코드를 구현하는 50가지 전략과 기법",
      "나의 라임오렌지나무:어느 날 슬픔을 발견한 한 꼬마의 이야기",
    ],
  },

  {
    major: "평생교육학과",
    grade: "12학번",
    bookList: [
      "노동법 사례연습 =Labor law case study",
      "(역량평가와 역량개발 피드백을 위한)평가센터 =Assessment center :theory·model·methodology",
      "(MG새마을금고 채용 지역본부) 경영학",
      "교육행정 및 학교경영의 이해",
      "(2016 공인노무사) 기출·사례 행정쟁송법",
      "인사관리 기본강의 =Human resource management",
      "노동법 :사례연습",
      "(2016 공인노무사) 쟁점정리 행정쟁송법",
      "(현대) 사회학 이론과 그 고전적 뿌리",
      "면접의 달인:2010 실전 편",
    ],
  },
  {
    major: "평생교육학과",
    grade: "13학번",
    bookList: [
      "101 ways to make training active",
      "여름 별장, 그 후",
      "(전한길) 한국사 :2.0 All in one",
      "(2019 선재국어) 한 권으로 정리하는 마무리",
      "공간의 가치 =The Value of space :한국 상업용 주거용 부동산의 구조적 이해",
      "(2016 하반기 위포트) HMAT 현대자동차 직무적성검사 :최신기출유형분석 + 실전 모의고사",
      "봉순이 언니 :공지영 장편소설",
      "시나리오 어떻게 쓸 것인가",
      "행운에 속지 마라 :불확실한 시대에 살아남는 투자 생존법",
      "이동기 영어.1-3",
    ],
  },
  {
    major: "평생교육학과",
    grade: "14학번",
    bookList: [
      "혼불 :대하소설.1-10",
      "101 ways to make training active",
      "노인복지론",
      "해커스 텝스 보카",
      "주식투자 무작정 따라하기",
      "성인학습 및 상담",
      "뉴미디어와 정보사회 =New media in the information society",
      "건축시공학 :최신 건축기술 및 공법 중심의 실무서 =Building construction",
      "(무료 동영상과 함께하는) 한국사능력검정시험 :1.2급 고급 :3단계 기출분석집+모의고사",
      "발달심리학 =Developmental psychology",
    ],
  },
  {
    major: "평생교육학과",
    grade: "15학번",
    bookList: [
      "E-learning by design",
      "101 ways to make training active",
      "평생교육경영론",
      "당신, 거기 있어줄래요? :기욤 뮈소 장편소설",
      "생활지도 및 상담",
      "데미안",
      "진로 탐색 및 직업 선택 :NCS 직업기초능력의 이해와 실습",
      "경영정보시스템",
      "의자놀이 :공지영의 첫 르포르타주 쌍용자동차 이야기",
      "사랑의 기술",
    ],
  },
  {
    major: "평생교육학과",
    grade: "16학번",
    bookList: [
      "리더십 :이론과 실제",
      "미시경제학",
      "(평생학습사회 실현을 위한) 성인학습 및 상담 =Adult learning and counselling",
      "리더십의 이론과 실제",
      "리더십",
      "평생교육경영론",
      "E-learning by design",
      "Leadership :theory and practice",
      "(No plan! No problem!) Enjoy 도쿄",
      "미시경제학:수학노트와 연습문제 해답",
    ],
  },
  {
    major: "평생교육학과",
    grade: "17학번",
    bookList: [
      "(성공하는 사람들의)7가지 습관",
      "평생교육경영론",
      "변하는 것과 변하지 않는 것 :인문학적 마케팅 사고방식 :back to the basic",
      "예술치료",
      "리더십 :이론과 실제",
      "모모",
      "문학을 사랑하는 젊은이들에게",
      "허수아비춤 :조정래 장편소설",
      "그것은 사랑이 아니다",
      "설득의 심리학 :작은 시도로 큰 변화를 이끌어내는 '스몰 빅'의 놀라운 힘완결편",
    ],
  },
  {
    major: "평생교육학과",
    grade: "18학번",
    bookList: [
      "구해줘 :기욤 뮈소 장편소설",
      "차라투스트라는 이렇게 말했다",
      "데미안",
      "(아름다운 빈손)한경직",
      "(S line) 전산회계 1급",
      "지적 대화를 위한 넓고 얕은 지식 :한 권으로 현실 세계를 통달하는 지식 여행서",
      "평생교육경영론 :평생교육기관 경영의 성과극대화를 위한",
      "인도기행=India",
      "자유론",
      "당신, 거기 있어줄래요? :기욤 뮈소 장편소설",
    ],
  },
  {
    major: "평생교육학과",
    grade: "19학번",
    bookList: [
      "(친절한) 회계원리",
      "다문화교육과 평생교육 :이론과 실제 :한국, 영국, 캐나다, 호주 현장 사례 분석",
      "니코마코스 윤리학",
      "된다! 네이버 블로그 & 포스트: 만들기부터 검색 상위 노출까지!: 2019년판 블로그 마케팅 교과서!",
      "(내 안의 위대한 혁명) 서번트 리더십=(The)servant leadership",
      "교육평가",
      "(2018 시나공) 컴퓨터활용능력 1급 필기",
      "경영정보시스템의 이해",
      "(해커스) 전산회계 1급 :이론+실기+기출문제",
      "신인사관리 :노동과 자본의 통합이론",
    ],
  },
  {
    major: "평생교육학과",
    grade: "20학번",
    bookList: [
      "데미안",
      "프레임 :나를 바꾸는 심리학의 지혜",
      "너, 외롭구나 :김형태의 청춘 카운슬링",
      "제자도",
      "무역상무 =International commercial transaction",
      "위대한 개츠비",
      "영적 지도력 :하나님께 쓰임 받는 리더들의 실제적 지침서 :리더들이여, 계속해서 열심을 품으라!",
      "정신건강론",
      "나는 소망한다 내게 금지된 것을 :양귀자 장편소설",
      "주님의 전도 계획",
    ],
  },
  {
    major: "평생교육학과",
    grade: "21학번",
    bookList: [
      "너, 외롭구나 :김형태의 청춘 카운슬링",
      "회계기초 탈출기 15일 플랜!     :회계사 아빠와 왕초보 딸의 재밌는 회계 수다",
      "그 청년 바보의사",
      "이것이 LEET 논술이다!: 유형·주제 통합편",
      "(원조 유튜브 원어민 강사 마이클쌤의) 리얼 영어회화",
      "놀라운 하나님의 은혜",
      "해커스 토익 Listening + Reading 세트 (2018 최신개정판)",
      "회계기초 탈출기 :회계사 아빠와 왕초보 딸의 재밌는 회계 수다",
      "Zoo animals :behaviour, management and welfare",
      "누가 돌을 옮겼는가? :그리스도의 최후 일주일 추적",
    ],
  },
  {
    major: "행정학부",
    grade: "21학번",
    bookList: [
      "군주론",
      "해방전후사의 인식.1 - 6",
      "정책평가:이론과 적용",
      "(황장엽) 回顧錄(회고록)",
      "홋카이도",
      "글로벌 무역학개론",
      "리더십 :이론과 실제",
      "지방행정론",
      "정책분석론",
      "이탈리아 =Italia :2018~2019 최신개정판",
    ],
  },
  {
    major: "행정학부",
    grade: "13학번",
    bookList: [
      "정책분석론",
      "정책평가론",
      "도시행정론 :이론과 정책",
      "정책집행론 =Policy implementation",
      "새 인사행정론 =Public personnel administration",
      "정책학 :이론과 경험적 연구",
      "(신영식) 해동한국사",
      "정책평가:이론과 적용",
      "(전한길 한국사) 4.0: 실전동형 모의고사",
      "갈등관리와 협상전략론",
    ],
  },
  {
    major: "행정학부",
    grade: "14학번",
    bookList: [
      "정책분석론",
      "정책학원론=Theories of policy sciences",
      "새 인사행정론 =Public personnel administration",
      "정책학원론 =Theories of policy sciences",
      "기획론",
      "지방행정론",
      "행정법개론",
      "청소년비행론",
      "재무행정론",
      "Organizational behavior :managing people and organizations",
    ],
  },
  {
    major: "행정학부",
    grade: "15학번",
    bookList: [
      "정책분석론",
      "기획론",
      "정책평가:이론과 적용",
      "지방행정론",
      "정책평가론",
      "(조민혁의) 합격을 부르는 자소서",
      "정책학원론 =Theories of policy sciences",
      "정책집행론 =Policy implementation",
      "행정기획론",
      "당신, 거기 있어줄래요? :기욤 뮈소 장편소설",
    ],
  },
  {
    major: "행정학부",
    grade: "16학번",
    bookList: [
      "행정조사방법론=Research Methods for Public Administration",
      "정책학 :이론과 경험적 연구",
      "정책학원론 =Theories of policy sciences",
      "정책분석론",
      "새 조직론",
      "정책평가론",
      "정책학원론 =Theories of policy science",
      "(새) 조직론 =New Perspectives on Organization",
      "지방행정론",
      "도시행정론 :이론과 정책",
    ],
  },
  {
    major: "행정학부",
    grade: "17학번",
    bookList: [
      "정책학원론 =Theories of policy sciences",
      "재무행정론",
      "행정이론 :행정사와 이론을 중심으로",
      "맨큐의 경제학",
      "행정관리론",
      "도시행정론: 이론과 정책",
      "지방행정론",
      "정책분석론",
      "정책평가론",
      "재무행정론 =Public budgeting & finance",
    ],
  },
  {
    major: "행정학부",
    grade: "18학번",
    bookList: [
      "정책학원론",
      "행정관리론",
      "정책학원론 =Theories of policy sciences",
      "새 인사행정론 =Public personnel administration",
      "도시행정론: 이론과 정책",
      "정책학원론 =Theories of policy science",
      "행정조사방법론=Research Methods for Public Administration",
      "정책학 :이론과 경험적 연구",
      "새 인사행정론=Public personnel administration",
      "정책평가론",
    ],
  },
  {
    major: "행정학부",
    grade: "19학번",
    bookList: [
      "행정이론 :행정사와 이론을 중심으로",
      "정책학원론",
      "민주주의",
      "맨큐의 경제학",
      "(새) 조직론 =New Perspectives on Organization",
      "글로벌 무역학개론",
      "사랑의 기술",
      "도시행정론: 이론과 정책",
      "재무행정학",
      "(시사와 함께하는) 거시경제학",
    ],
  },
  {
    major: "행정학부",
    grade: "20학번",
    bookList: [
      "행정관리론",
      "통계학 =Statistics",
      "(다시 읽고 싶은) 한국행정학 좋은논문 12선",
      "경제학 들어가기 =Introductory economics",
      "(新) 행정조직론=Administrative organizations",
      "재무행정론",
      "정보 보안 개론   :한 권으로 배우는 핵심 보안 이론",
      "멋진 신세계",
      "(2021) 핵심정리 행정법",
      "헌법중요판례 250 :[제6판/2018년]",
    ],
  },
  {
    major: "행정학부",
    grade: "21학번",
    bookList: [
      "나의 라임오렌지나무:어느 날 슬픔을 발견한 한 꼬마의 이야기",
      "(새) 행정학",
      "동물 해방",
    ],
  },

  {
    major: "혁신경영학과(계약학과)",
    grade: "14학번",
    bookList: [
      "미녀는 괴로워",
      "뽑히는 자기소개서",
      "연애의 목적",
      "(학예사를 위한) 전시기획입문",
      "강아지똥",
      "우리들의 행복한 시간",
      "캐릭터 소설 쓰는 법 :살아있는캐릭터만들기",
      "말아톤",
    ],
  },
  {
    major: "혁신경영학과(계약학과)",
    grade: "15학번",
    bookList: [
      "시크릿 Bangkok :로컬이 인정하는 방콕의 비밀 명소",
      "고도몰 무료 쇼핑몰 만들기",
      "(프렌즈) 방콕 =Bangkok",
      "(모던 웹을 위한) JavaScript jQuery 입문",
      "스프링 5 레시피 :스프링 애플리케이션 개발에 유용한 161가지 문제 해결 기법",
      "코딩 인터뷰 완전 분석   :189가지 프로그래밍 문제와 해법",
    ],
  },
  {
    major: "혁신경영학과(계약학과)",
    grade: "19학번",
    bookList: ["Principles of marketing"],
  },
  {
    major: "화학공학과",
    grade: "12학번",
    bookList: [
      "(적중) 화공기사",
      "(쉽고 빠른 단기 합격 전략) 수질환경기사/산업기사",
      "(단 한권으로 마무리하는) 위험물산업기사 :필기·실기",
      "단위조작",
      "(프로젝트 기반의) 공학설계입문",
      "Transport phenomena",
      "Fundamentals of momentum, heat and mass transfer",
      "기체·액체 크로마토그래피 및 질량 분석학",
      "최신공정제어공학 :MATLAB의 활용과 실습",
      "LG그룹 인·적성검사 :종합편",
    ],
  },
  {
    major: "화학공학과",
    grade: "13학번",
    bookList: [
      "Fundamentals of momentum, heat and mass transfer",
      "(적중) 화공기사",
      "(McMurry) 기본유기화학",
      "(2주 만에 끝내는)해커스 토익 speaking :Level 7·8",
      "기초 이동현상론 :운동량, 열 및 물질전달",
      "단위조작",
      "Unit Operation of Chemical Engineering",
      "최신공정제어공학 :MATLAB의 활용과 실습",
      "Modern semiconductor devices for integrated circuits",
      "디스플레이 공학개론 =Introduction to display engineering",
    ],
  },
  {
    major: "화학공학과",
    grade: "14학번",
    bookList: [
      "고분자화학",
      "Water and wastewater technology",
      "(적중) 화공기사",
      "전기화학",
      "Basic principles and calculations in chemical engineering",
      "기초 이동현상론 :운동량, 열 및 물질전달",
      "Fundamentals of momentum, heat and mass transfer",
      "Wastewater engineering :treatment and reuse",
      "최신공정제어공학 :MATLAB의 활용과 실습",
      "(No.1) 화공기사 :필기 =Engineer chemical industry",
    ],
  },
  {
    major: "화학공학과",
    grade: "15학번",
    bookList: [
      "재료과학",
      "Fundamentals of momentum, heat and mass transfer",
      "최신공정제어공학 :MATLAB의 활용과 실습",
      "(적중) 화공기사",
      "단위조작",
      "기초 이동현상론 :운동량, 열 및 물질전달",
      "디스플레이 공학개론 =Introduction to display engineering",
      "Principles of polymerization",
      "(No.1) 화공기사 :필기 =Engineer chemical industry",
      "(표준)일반화학실험",
    ],
  },
  {
    major: "화학공학과",
    grade: "16학번",
    bookList: [
      "Fundamentals of organic chemistry",
      "Introduction to environmental engineering and science",
      "재료과학",
      "분석화학실험=Experimental analytical chemistry",
      "(Kreyszig) 공업수학",
      "(Kreyszig 공업수학) 문제풀이 해설",
      "Basic principles and calculations in chemical engineering",
      "(가장 쉬운) 스페인어 첫걸음의 모든 것 :회화편＋문법편",
      "콜로이드와 계면활성제",
      "보통의 존재 :이석원 산문집",
    ],
  },
  {
    major: "화학공학과",
    grade: "17학번",
    bookList: [
      "(표준)일반화학실험",
      "재료과학",
      "콜로이드와 계면활성제",
      "일반화학실험",
      "전기화학",
      "기초 이동현상론 :운동량, 열 및 물질전달",
      "예루살렘의 아이히만",
      "정량분석화학",
      "열전달",
      "일반화학",
    ],
  },
  {
    major: "화학공학과",
    grade: "18학번",
    bookList: [
      "(Kreyszig) 공업수학",
      "미분적분학 =Calculus",
      "(McMurry) 기본유기화학",
      "이기적 유전자 :진화론의 새로운 패러다임",
      "재료과학",
      "콜로이드와 계면활성제",
      "일반화학",
      "Fundamentals of organic chemistry",
      "분석화학실험 =Experiments in analytical chemistry",
      "전기화학",
    ],
  },
  {
    major: "화학공학과",
    grade: "19학번",
    bookList: [
      "최신공정제어공학 :MATLAB의 활용과 실습",
      "디스플레이 공학개론 =Introduction to display engineering",
      "재료과학",
      "(최신) 공정제어공학 :MATLAB의 활용과 실습 =Advanced process control systems : analysis & design",
      "(Kreyszig) 공업수학",
      "일반화학",
      "기초 이동현상론 :운동량, 열 및 물질전달",
      "(Kreyszig 공업수학) 문제풀이 해설",
      "분석화학실험=Experimental analytical chemistry",
      "(최적합) ACA 포토샵CC =Adobe Certified Associate & Photoshop CC :국제인증 자격증",
    ],
  },
  {
    major: "화학공학과",
    grade: "20학번",
    bookList: [
      "(Kreyszig) 공업수학",
      "Basic principles and calculations in chemical engineering",
      "(표준)일반화학실험",
      "Chemical technicians' ready reference handbook",
      "콜로이드와 계면활성제",
      "멋진 신세계",
      "유기화학",
      "호숫가 살인사건",
      "(맥머리의) 유기화학강의",
      "(옥스토비의) 일반화학",
    ],
  },
  {
    major: "화학공학과",
    grade: "21학번",
    bookList: [
      "재료과학",
      "(열혈강의) 다양한 예제로 완성하는 C 포인터 :C포인터개념완벽이식",
      "사이버범죄학 =Cyber criminology :원인/유형/대책",
      "행복한 이기주의자",
      "역사란 무엇인가",
    ],
  },

  {
    major: "화학과",
    grade: "12학번",
    bookList: [
      "무기화학",
      "Introduction to solid state physics",
      "물리화학실험",
      "Atkins' physical chemistry",
      "Inorganic chemistry",
      "Shriver ＆ Atkins' inorganic chemistry",
      "Lehninger principles of biochemistry",
      "오사카 100배 즐기기 =Osaka :교토·고베·나라·와카야마",
      "기계설계",
      "철도신호해설 =Railway signal commentary :철도시스템 이해를 위한 최적의 철도종합실무서",
    ],
  },
  {
    major: "화학과",
    grade: "13학번",
    bookList: [
      "무기화학",
      "Principle of Instrumental Analysis",
      "Atkins' physical chemistry",
      "캐나다",
      "물리화학실험",
      "Spectrometric identification of organic compounds",
      "기기분석의 원리",
      "Organic chemistry :an intermediate text",
      "(레닌저) 생화학",
      "Inorganic chemistry",
    ],
  },
  {
    major: "화학과",
    grade: "14학번",
    bookList: [
      "무기화학",
      "(레닌저) 생화학",
      "물리화학실험",
      "Inorganic chemistry",
      "Lehninger principles of biochemistry",
      "Student solutions manual to accompany Atkins' physical chemistry",
      "Atkins' physical chemistry",
      "(파비아의) 분광학강의",
      "교육평가의 이해 =Educational evaluation",
      "(합격이 보이는) 화학분석기사   :필기",
    ],
  },
  {
    major: "화학과",
    grade: "15학번",
    bookList: [
      "(레닌저) 생화학",
      "물리화학실험",
      "무기화학",
      "Student solutions manual to accompany Atkins' physical chemistry",
      "(최신 화학분석기사) 주관식 작업형",
      "Lehninger principles of biochemistry",
      "Introduction to spectroscopy",
      "Inorganic chemistry",
      "기기분석 =Instrumental analysis",
      "(No.1) 화공기사 :필기 =Engineer chemical industry",
    ],
  },
  {
    major: "화학과",
    grade: "16학번",
    bookList: [
      "(레닌저) 생화학",
      "무기화학",
      "유기화학",
      "(다시 쓴) 유기화학 실험",
      "Introduction to spectroscopy",
      "유기화학실험",
      "유기화학 실험",
      "Mit Erfolg zum TestDaF :Ubungs- und Testbuch",
      "(옥스토비의) 일반화학",
      "Quantum chemistry",
    ],
  },
  {
    major: "화학과",
    grade: "17학번",
    bookList: [
      "분석화학실험=Experimental analytical chemistry",
      "유기화학실험",
      "물리화학실험",
      "(다시 쓴) 유기화학 실험",
      "데미안",
      "무기화학",
      "(표준)일반화학실험",
      "코인로커 베이비스=Coin locker babies:무라카미 류 장편소설",
      "(맥머리의) 유기화학",
      "일반화학실험",
    ],
  },
  {
    major: "화학과",
    grade: "18학번",
    bookList: [
      " 유기화학실험",
      "(파비아의) 분광학강의",
      "교육심리학 =Educational psychology",
      "(레닌저) 생화학",
      "(옥스토비의) 일반화학",
      "Atkins' physical chemistry",
      "분석화학 입문",
      "(스쿠그의) 기기분석의 이해",
      "내가 죽으면 장례식에 누가 와줄까",
      "화학 교재 연구 및 지도",
    ],
  },
  {
    major: "화학과",
    grade: "19학번",
    bookList: [
      "유기화학실험",
      "환경화학",
      "분석화학실험=Experimental analytical chemistry",
      "물리화학실험",
      "변신 :카프카 단편선",
      "일반화학",
      "회색인",
      "Student solutions manual to accompany Atkins' physical chemistry",
      "변신:단편전집",
      "해커스 토익 실전 1000제 :listening :문제집.1",
    ],
  },
  {
    major: "화학과",
    grade: "20학번",
    bookList: [
      "십대의 5가지 사랑의 언어",
      "(교육학적 사유를 여는) 교육의 철학과 역사",
      "최신교육학개론 =Introduction to education",
      "자녀의 5가지 사랑의 언어",
      "대학생을 위한 활용 독일어 =Lebendiges Deutsch f?r Studenten",
      "코스모스",
    ],
  },
  {
    major: "화학과",
    grade: "21학번",
    bookList: [
      "해석학 입문",
      "개미:베르나르 베르베르 장편소설",
      "인간 실격",
      "100세 인생 :전혀 다른 시대를 준비하는 새로운 인생 설계 전략",
      "(알기 쉬운)선형대수",
      "해석개론 =Introduction to analysis",
      "개미 :베르나르 베르베르 장편소설",
      "Biology :a global approach",
      "파리 대왕",
      "이기적 유전자 :진화론의 새로운 패러다임",
    ],
  },
  {
    major: "회계학과",
    grade: "12학번",
    bookList: [
      "세법개론",
      "(2018 공인회계사 기출문제집 1차) 회계학",
      "(2019) 세법개론 =Tax law",
      "IFRS 고급회계 =Advanced accounting",
      "(2018 국가공인) 재경관리사 :K-IFRS 재무회계",
      "(IFRS) 고급회계 =International financial reporting standards advanced accounting",
      "(2018) 세법개론",
      "(2017 login) 전산세무 1급 :기출문제 및 핵심요약",
      "정부회계학 :국가회계와 지방회계 =Governmental accounting",
      "IFRS 고급회계 =IFRS Advanced accounting",
    ],
  },
  {
    major: "회계학과",
    grade: "13학번",
    bookList: [
      "재무관리 =Financial management",
      "경제학 연습 :미시편",
      "(2018) 세무회계연습",
      "재정학 연습 =Public finance",
      "(IFRS) 중급회계 =Intermediate accounting",
      "(2018) 객관식 세법 =Tax law",
      "경제학 연습 :거시편",
      "경제학 강의 =Economics",
      "(New) ISA 회계감사 =2019 New International Standards on Auditing",
      "기초 경제수학특강:For beginners",
    ],
  },
  {
    major: "회계학과",
    grade: "14학번",
    bookList: [
      "세법개론",
      "(객관식) 세법 =Multiple choice tax law",
      "다이어트 경제학 보충자료집",
      "IFRS 고급회계 =IFRS Advanced accounting",
      "(IFRS) 중급회계 =Intermediate accounting",
      "정부회계학 :국가회계와 지방회계 =Governmental accounting",
      "IFRS 중급회계 :연습문제해설",
      "(2018) 세법개론",
      "경제학 연습 :미시편",
      "(객관식 다이어트) 경제학 :거시편",
    ],
  },
  {
    major: "회계학과",
    grade: "15학번",
    bookList: [
      "세법개론",
      "글로벌 무역학개론",
      "(하루에 끝장내기) 세법 .2018",
      "(2018) 세법개론",
      "(2019) 객관식 세법 =Tax law",
      "재무관리",
      "재무관리연습 =Advanced Financial management",
      "IFRS 고급회계 =IFRS Advanced accounting",
      "(IFRS) 하루에 끝장내기 재무회계 :2021년 공인회계사·세무사 1차 대비",
      "(합격으로 가는 최단 코스) 재경관리사 :한권으로 끝내기 :2021 최신개정판",
    ],
  },
  {
    major: "회계학과",
    grade: "16학번",
    bookList: [
      "IFRS 중급 회계 =International financial reporting standards intermediate accounting",
      "IFRS 중급회계 =International Financial Reporting Standards intermediate accounting",
      "전략적 관리회계 =Strategic management accounting",
      "(합격으로 가는 최단 코스) 재경관리사 :한권으로 끝내기 :2021 최신개정판",
      "(2019) 세무회계연습 =Tax accounting",
      "IFRS 고급회계 =Advanced accounting",
      "(2019) 객관식 재무회계 =Financial accounting :중급회계",
      "우리는 사랑일까 :알랭 드 보통 장편소설",
      "(2021) 객관식 세법 =Tax law",
      "객관식 세법",
    ],
  },
  {
    major: "회계학과",
    grade: "17학번",
    bookList: [
      "정부회계학=Government accounting :국가회계와 지방회계",
      "(2019) 세법개론 =Tax law",
      "CPA 2차 원가관리회계 =Cost & management accounting: CPA 2차 시험 대비 연습서",
      "전략적 관리회계 =Strategic management accounting",
      "(2019) 객관식 재무회계 =Financial accounting :중급회계",
      "IFRS 중급회계 =International financial reporting standards  intermediate accounting",
      "(2019) 객관식 세법 =Tax law",
      "자유론",
      "경제학원론 =Economics",
      "원가관리회계 =Cost & management accounting",
    ],
  },
  {
    major: "회계학과",
    grade: "18학번",
    bookList: [
      "사람의 아들:이문열 장편소설",
      "IFRS 중급 회계 =International financial reporting standards intermediate accounting",
      "세법개론",
      "IFRS 고급회계=Advanced accounting",
      "경제학 연습 :거시편",
      "선물",
      "자유론",
      "IFRS 고급회계 =Advanced accounting",
      "IFRS 중급회계 =International Financial Reporting Standards intermediate accounting",
      "무소유",
    ],
  },
  {
    major: "회계학과",
    grade: "19학번",
    bookList: [
      "사랑의 기술",
      "(2019) 세법개론 =Tax law",
      "과학기술의 철학적 이해",
      "공인회계사 기출문제집 :2018년 최신판",
      "Corporate finance",
      "IFRS 회계원리=International financial reporting standards accounting principles",
      "간디 자서전 :나의 진리실험 이야기",
      "(유쾌한)회계상식:기본편",
      "한국문학통사",
      "IFRS 중급회계 =International financial reporting standards  intermediate accounting",
    ],
  },
  {
    major: "회계학과",
    grade: "20학번",
    bookList: [
      "(IFRS) 중급회계 =Intermediate accounting",
      "눈사람 자살 사건",
      "IFRS 중급회계 =International Financial Reporting Standards intermediate accounting",
      "향수 :어느 살인자의 이야기 :파트리크 쥐스킨트 장편소설",
      "교양노동법",
      "호밀밭의 파수꾼",
      "현대 패션과 의생활=Fashion ＆ Clothing",
      "뇌:베르나르 베르베르 장편소설",
      "수학 세상 가볍게 읽기",
      "부끄러움을 가르칩니다:박완서 소설",
    ],
  },
  {
    major: "회계학과",
    grade: "21학번",
    bookList: [
      "회계원리 =Accounting principle",
      "(처음 만나는) 인공지능 =Welcome to the A.I. world",
      "왕은 사랑한다 :김이령 장편소설",
      "(의사결정을 위한) 현대통계학",
      "백년허리 :백년 동안 간직할 허리 사용설명서",
      "(친절한) 재무회계 =Financial accounting",
      "三國志",
    ],
  },
];
