export const majorList = [
  "경영학부",
  "의생명시스템학부",
  "국제법무학과",
  "소프트웨어학부",
  "중어중문학과",
  "화학공학과",
  "행정학부",
  "컴퓨터학부",
  "혁신경영학과(계약학과)",
  "독어독문학과",
  "예술창작학부 영화예술전공",
  "정보사회학과",
  "스포츠학부",
  "사학과",
  "수학과",
  "경제학과",
  "예술창작학부 문예창작전공",
  "금융경제학과",
  "화학과",
  "금융학부",
  "AI융합학부",
  "국제무역학과",
  "국어국문학과",
  "산업·정보시스템공학과",
  "미디어경영학과",
  "영어영문학과",
  "정치외교학과",
  "법학과",
  "회계학과",
  "불어불문학과",
  "글로벌통상학과",
  "일어일문학과",
  "언론홍보학과",
  "벤처중소기업학과",
  "융합특성화자유전공학부",
  "정보통신전자공학부",
  "건축학부",
  "전자정보공학부 전자공학전공",
  "물리학과",
  "벤처경영학과(계약학과)",
  "사회복지학부",
  "정보통계·보험수리학과",
  "전자정보공학부 IT융합전공",
  "평생교육학과",
  "복지경영학과(계약학과)",
  "기독교학과",
  "기계공학부",
  "글로벌미디어학부",
  "전기공학부",
  "유기신소재·파이버공학과",
  "철학과",
];

export const gradeList = [
  "12학번",
  "13학번",
  "14학번",
  "15학번",
  "16학번",
  "17학번",
  "18학번",
  "19학번",
  "20학번",
  "21학번",
];

// {
//   major: "",
//   bookList: ["", "", "", "", "", "", "", "", "", ""],
// },

// 학과별 추천 리스트
export const byMajorList = [
  {
    major: "경영학부",
    bookList: [
      "Essentials of investments",
      "경제학원론 =Economics",
      "조직과 리더십 =Organization & leadership",
      "경영전략 =Strategic management",
      "경영학원론",
      "서비스 마케팅 =Service marketing",
      "왜 나는 너를 사랑하는가",
      "참을 수 없는 존재의 가벼움",
      "(친절한) 재무회계 =A gentle introduction to Introduce financial accounting",
      "(친절한) 재무회계=Financial accounting",
    ],
  },
  {
    major: "의생명시스템학부",
    bookList: [
      "An introduction to biostatistics",
      "(레닌저) 생화학",
      "Genetics :a conceptual approach",
      "분자 세포 생물학",
      "Fundamentals of organic chemistry",
      "The immune system",
      "생명과학",
      "(McMurry) 기본유기화학",
      "(알기 쉬운)선형대수",
      "Molecular cell biology",
    ],
  },
  {
    major: "국제법무학과",
    bookList: [
      "국제법 판례 100선 =International law cases",
      "민사소송법",
      "형사소송법",
      "신국제법강의 :이론과 사례",
      "Evidence",
      "Criminal law",
      "International organizations :the politics and processes of global governance",
      "Principles of international business transactions",
      "(객관식) 국제법",
      "(요건사실 중심)분쟁유형별 민사법",
    ],
  },
  {
    major: "소프트웨어학부",
    bookList: [
      "(Do it!) Node.js 프로그래밍 :실제 서버로 구동 가능한 코드로 배운다!",
      "자바 네트워크 프로그래밍",
      "(Do it!) 자바스크립트+제이쿼리 입문  :155개 예재로 기본 잡고, 반응형 웹부터 실무 활용 플러그인까지!",
      "(명품) Java programming",
      "(Do it!) 안드로이드 앱 프로그래밍 :안드로이드 8.0 오레오 버전 반영판!",
      "(명품) JAVA programming",
      "(쉽게 배우는) 데이터 통신과 컴퓨터 네트워크",
      "(Do it!) HTML5+CSS3 웹 표준의 정석",
      "(Do it!) 안드로이드 앱 프로그래밍 :안드로이드 7.0 누가 버전·안드로이드 스튜디오 반영판!",
      "(Rosen의) 이산수학",
    ],
  },
  {
    major: "중어중문학과",
    bookList: [
      "(왜? 라는 질문에 속시원히 답해주는) 중국어 문법책",
      "공자의 생애와 사상",
      "시를 잊은 그대에게",
      "(쉽게 알고 배우는) 易知 한자 :상공회의소 2급 기본서",
      "중국문학사",
      "(쉽게 알고 배우는) 易知 한자 :상공회의소 2급 최종모의고사",
      "참을 수 없는 존재의 가벼움",
      "논어",
      "왜 나는 너를 사랑하는가",
      "(쉽게 알고 배우는) 상공회의소 易知 한자 :2급",
    ],
  },
  {
    major: "화학공학과",
    bookList: [
      "재료과학",
      "(적중) 화공기사",
      "최신공정제어공학 :MATLAB의 활용과 실습",
      "(Kreyszig) 공업수학",
      "Fundamentals of momentum, heat and mass transfer",
      "기초 이동현상론 :운동량, 열 및 물질전달",
      "Fundamentals of organic chemistry",
      "콜로이드와 계면활성제",
      "전기화학",
      "일반화학",
    ],
  },
  {
    major: "행정학부",
    bookList: [
      "정책분석론",
      "정책학원론 =Theories of policy sciences",
      "정책평가론",
      "지방행정론",
      "정책평가:이론과 적용",
      "정책학 :이론과 경험적 연구",
      "행정이론 :행정사와 이론을 중심으로",
      "기획론",
      "정책학원론",
      "정책학원론=Theories of policy sciences",
    ],
  },
  {
    major: "컴퓨터학부",
    bookList: [
      "(명품) Java programming",
      "(Do it!) Node.js 프로그래밍 :실제 서버로 구동 가능한 코드로 배운다!",
      "(Rosen의) 이산수학",
      "(윤성우의 열혈) C++ 프로그래밍",
      "Concepts of programming languages",
      "(윤성우의 열혈) TCP/IP 소켓 프로그래밍",
      "Java의 정석",
      "코딩 인터뷰 완전 분석   :189가지 프로그래밍 문제와 해법",
      "(2017) 정보처리기사 :실기(산업기사 포함) 기본서",
      "(모던 웹을 위한) Node.js 프로그래밍",
    ],
  },
  {
    major: "혁신경영학과(계약학과)",
    bookList: [
      "Principles of marketing",
      "강아지똥",
      "미녀는 괴로워",
      "(모던 웹을 위한) JavaScript jQuery 입문",
      "말아톤",
      "(학예사를 위한) 전시기획입문",
      "시크릿 Bangkok :로컬이 인정하는 방콕의 비밀 명소",
      "스프링 5 레시피 :스프링 애플리케이션 개발에 유용한 161가지 문제 해결 기법",
      "뽑히는 자기소개서",
      "코딩 인터뷰 완전 분석   :189가지 프로그래밍 문제와 해법",
    ],
  },
  {
    major: "독어독문학과",
    bookList: [
      "향수 :어느 살인자의 이야기 :파트리크 쥐스킨트 장편소설",
      "데미안",
      "모래 사나이",
      "파우스트",
      "토니오 크뢰거 :토마스 만 단편선",
      "깊이에의 강요",
      "獨逸文學思潮史",
      "詩學",
      "니벨룽겐의 노래",
      "(북유럽 신화)에다 :게르만 민족의 신화, 영웅전설, 생활의 지혜",
    ],
  },
  {
    major: "예술창작학부 영화예술전공",
    bookList: [
      "시나리오 어떻게 쓸 것인가",
      "영화조명핸드북",
      "왜 나는 너를 사랑하는가",
      "참을 수 없는 존재의 가벼움",
      "이갈리아의 딸들",
      "친절한 금자씨",
      "데미안",
      "예술가여, 무엇이 두려운가!",
      "사랑의 기술",
      "시나리오란 무엇인가",
    ],
  },
  {
    major: "정보사회학과",
    bookList: [
      "사이버범죄학 =Cyber criminology :원인/유형/대책",
      "사회조사방법론",
      "이기적 유전자 :진화론의 새로운 패러다임",
      "국가란 무엇인가",
      "사회조사 분석사 2급 :2차 실기 :한권으로 끝내기",
      "이기적 유전자",
      "사회조사분석사 +α :2급 실기 필답형(논술형)",
      "사회조사분석사 :2급 필기 :한권으로 올인하기",
      "멋진 신세계",
      "(SPSS) 사회조사분석사 :2급 2차 실기",
    ],
  },
  {
    major: "스포츠학부",
    bookList: [
      "스포츠마케팅 =Sport marketing",
      "요가 아나토미 :해부학적으로 쉽게 배우는 요가",
      "아헹가 요가:몸과 영혼의 해탈에 이르는 길",
      "(Enger) 생명과학",
      "(NASM의) 퍼스널 트레이닝",
      "달과 6펜스",
      "사회체육지도론",
      "스타팅 스트렝스 :기본 바벨 훈련",
      "현대여가학=Modern leisure studies",
      "(생활체육지도자용) 퍼펙트 웨이트트레이닝",
    ],
  },
  {
    major: "사학과",
    bookList: [
      "인생:위화 장편소설",
      "東洋史槪論",
      "한국 고고학 강의",
      "서양사강의",
      "중국사",
      "한국건축의 역사",
      "西洋史槪論",
      "역사란 무엇인가",
      "동양사개론",
      "아틀라스 중국사",
    ],
  },
  {
    major: "수학과",
    bookList: [
      "수학교육학신론",
      "Linear algebra and its applications",
      "선형 대수학과 그 응용",
      "Elementary number theory",
      "보험수리학 = Actuarial mathematics",
      "현대대수학",
      "Numerical mathematics and computing",
      "일반위상수학:이론과 연습",
      "Schaum's outline of theory and problems of set theory and related topics",
      "Mathematics for finance :an introduction to financial engineering",
    ],
  },
  {
    major: "경제학과",
    bookList: [
      "(시사와 함께하는) 거시경제학",
      "미시경제학",
      "미시경제학 :수학노트와 연습문제 해답",
      "재정학 =Public finance",
      "경제학 연습 :미시편",
      "Introduction to econometrics",
      "금융경제론 =(The) economics of money, banking and financial markets",
      "거시경제학",
      "생활경제 =Economy and life",
      "게임이론 길라잡이",
    ],
  },
  {
    major: "예술창작학부 문예창작전공",
    bookList: [
      "감시와 처벌:감옥의 역사",
      "참을 수 없는 존재의 가벼움",
      "하녀들",
      "인형의 집:헨리크 입센 희곡선집",
      "금각사",
      "입속의 검은 잎:기형도 시집",
      "대성당 :레이먼드 카버 소설",
      "단지 유령일 뿐",
      "오디세이아 :트로이 전쟁, 그 후 10년의 이야기",
      "변신 :카프카 단편선",
    ],
  },
  {
    major: "금융경제학과",
    bookList: [
      "미시경제학",
      "미시경제학 :수학노트와 연습문제 해답",
      "증권투자론 =Investments ＆ security analysis",
      "미시경제학 =Microeconomics",
      "(시사와 함께하는) 거시경제학",
      "거시경제학",
      "이갈리아의 딸들",
      "맨큐의 경제학",
      "(글로벌 시대의) 국제금융론 =International finance",
      "미시경제학:수학노트와 연습문제 해답",
    ],
  },
  {
    major: "화학과",
    bookList: [
      "무기화학",
      "(레닌저) 생화학",
      "물리화학실험",
      "유기화학실험",
      "Atkins' physical chemistry",
      "분석화학실험=Experimental analytical chemistry",
      "Student solutions manual to accompany Atkins' physical chemistry",
      "Lehninger principles of biochemistry",
      "(파비아의) 분광학강의",
      "Inorganic chemistry",
    ],
  },
  {
    major: "금융학부",
    bookList: [
      "맨큐의 경제학",
      "Options, futures, and other derivatives",
      "선물·옵션 투자의 이론과 전략",
      "파생상품의 평가와 헷징전략",
      "Principles of economics",
      "금융기관론 =Financial institutions management",
      "죽은 경제학자의 살아있는 아이디어",
      "Fundamentals of investments :valuation and management",
      "돈, 뜨겁게 사랑하고 차갑게 다루어라",
      "Financial markets and institutions",
    ],
  },
  {
    major: "AI융합학부",
    bookList: [
      "(알기 쉬운)선형대수",
      "UNIX 고급 프로그래밍",
      "전자회로",
      "컴퓨터 구조 및 설계 :하드웨어/소프트웨어 인터페이스",
      "Java의 정석",
      "(윤성우의 열혈) C++ 프로그래밍",
      "안드로이드 앱 프로그래밍 :T아카데미의 명강의를 한 권에 담았다!",
      "ROS 로봇 프로그래밍",
      "Digital design, with RTL design, VHDL, and Verilog",
      "(모두를 위한) 실용 전자공학 :기초부터 실무까지",
    ],
  },
  {
    major: "국제무역학과",
    bookList: [
      "거시경제학 =Macro economics",
      "마케팅관리론",
      "(新) 국제경제법 =International economic law",
      "(이훈영 교수의) 마케팅 조사론",
      "(프렌즈) 유럽 :베스트 시티 45 =Europe : best city 45",
      "총, 균, 쇠 :무기, 병균, 금속은 인류의 운명을 어떻게 바꿨는가",
      "중국경제론 =China economy",
      "국제운송물류 =International transportation & logistics",
      "수학 세상 가볍게 읽기",
      "신무역보험론",
    ],
  },
  {
    major: "국어국문학과",
    bookList: [
      "(최유찬의) 문예사조의 이해",
      "개념어 사전:인터넷에서도 검색할 수 없는 생생한 지식의 보물 창고",
      "국어음운론 개설",
      "한국현대문학사",
      "호모 루덴스:놀이와 문화에 관한 한 연구",
      "문학비평 용어사전",
      "나는 나를 파괴할 권리가 있다 :김영하 장편소설",
      "이갈리아의 딸들",
      "배비장전",
      "장끼전",
    ],
  },
  {
    major: "산업·정보시스템공학과",
    bookList: [
      "Introduction to operations research",
      "품질경영",
      "인간공학",
      "(No. 1 배극윤의) 품질경영기사 :필기",
      "Supply chain management :strategy, planning, and operation",
      "일반화학",
      "(No.1 배극윤의) 품질경영 기사 필기 =Engineer quality management",
      "공급사슬관리 =Supply chain management",
      "Arena를 이용한 시뮬레이션",
      "SQL 전문가 가이드 =(The)guide for SQL professional",
    ],
  },
  {
    major: "미디어경영학과",
    bookList: [
      "이갈리아의 딸들",
      "컴퓨터 그래픽스 배움터",
      "(최신)디지털미디어 원리 및 프로그래밍",
      "사랑의 기술",
      "(친절한) 회계원리",
      "Probability, random variables, and random signal principles",
      "이기적 유전자",
      "(에센스) 재무관리 =Financial management",
      "기독교와 현대사회",
      "(KS 규격에 따른) AutoCAD와 기계설계제도",
    ],
  },
  {
    major: "영어영문학과",
    bookList: [
      "캔터베리 이야기",
      "위대한 개츠비",
      "주홍글씨",
      "세일즈맨의 죽음",
      "English syntax and argumentation",
      "시스터 캐리",
      "유토피아",
      "검은 고양이 ...外",
      "프랑스 중위의 여자:존 파울즈 장편소설",
      "English :one tongue, many voices",
    ],
  },
  {
    major: "정치외교학과",
    bookList: [
      "역사란 무엇인가",
      "침묵",
      "죽은 경제학자의 살아있는 아이디어",
      "군주론",
      "감시와 처벌:감옥의 역사",
      "한국정치론 =Understanding Korean politics",
      "자유론",
      "제도분석 :이론과 쟁점",
      "국가란 무엇인가",
      "국제관계학:인간과 세계 그리고 정치",
    ],
  },
  {
    major: "법학과",
    bookList: [
      "국제법 판례 100선 =International law cases",
      "노동법 =Labour law",
      "국제법 판례 100선",
      "노동법",
      "(에센스) 노동법",
      "형사소송법",
      "행정법강의",
      "행정법강의 =Administrative law",
      "債權各論",
      "(객관식) 국제법",
    ],
  },
  {
    major: "회계학과",
    bookList: [
      "세법개론",
      "(IFRS) 중급회계 =Intermediate accounting",
      "(2019) 세법개론 =Tax law",
      "정부회계학 :국가회계와 지방회계 =Governmental accounting",
      "IFRS 중급 회계 =International financial reporting standards intermediate accounting",
      "IFRS 중급회계 =International financial reporting standards  intermediate accounting",
      "IFRS 고급회계 =Advanced accounting",
      "재무관리 =Financial management",
      "(2018) 세법개론",
      "경제학 연습 :거시편",
    ],
  },
  {
    major: "불어불문학과",
    bookList: [
      "어두운 상점들의 거리 :파트릭 모디아노 장편소설",
      "노트르담 드 파리",
      "피가로의 결혼",
      "참을 수 없는 존재의 가벼움",
      "델프 =DELF B2",
      "위대한 개츠비",
      "랑송 佛文學史",
      "이방인",
      "페드르",
      "미라보 다리",
    ],
  },
  {
    major: "글로벌통상학과",
    bookList: [
      "맨큐의 경제학",
      "해상보험",
      "중국경제론 =China economy",
      "(한주섭 교수의 최신) 화환신용장론",
      "(新) 국제경제법 =International economic law",
      "글로벌경영 =Global business management",
      "Global marketing",
      "총, 균, 쇠 :무기, 병균, 금속은 인류의 운명을 어떻게 바꿨는가",
      "미시경제학",
      "거시경제학 =Macro economics",
    ],
  },
  {
    major: "일어일문학과",
    bookList: [
      "구로사와 아키라의 영화세계",
      "참을 수 없는 존재의 가벼움",
      "설국",
      "상실의 시대",
      "구토",
      "영화의 이해",
      "국화와 칼:일본 문화의 틀",
      "경제학원론 =Economics",
      "침묵",
      "사랑의 기술",
    ],
  },
  {
    major: "언론홍보학과",
    bookList: [
      "매스미디어 연구방법론",
      "광고매체기획론 =Advertising media planning",
      "방송학 개론",
      "뉴미디어와 정보사회",
      "인간커뮤니케이션과 미디어 :소통공간의 확장",
      "광고학개론 =AnIntroduction to advertising",
      "사랑의 기술",
      "방송학개론",
      "데미안",
      "대중문화의 이해",
    ],
  },
  {
    major: "벤처중소기업학과",
    bookList: [
      "글로벌경영 =Global business management",
      "(친절한) 재무회계 =A gentle introduction to Introduce financial accounting",
      "전략적 브랜드관리=Strategic brand management :이론과 응용",
      "부자 아빠 가난한 아빠      :부자들이 들려주는 '돈'과 '투자'의 비밀",
      "왜 나는 너를 사랑하는가",
      "위대한 개츠비",
      "(이훈영교수의) 연구조사방법론=Research methodology",
      "전략적 관리회계 =Strategic management accounting",
      "경제학 연습 :미시편",
      "멋진 신세계",
    ],
  },
  {
    major: "융합특성화자유전공학부",
    bookList: [
      "신약성서는 오늘 우리에게 이렇게 증언한다:월요신학서당 편",
      "변신 :카프카 단편선",
      "영화로 읽는 정신분석  :김서영의 치유하는 영화읽기",
      "(새로 만든) 먼나라 이웃나라",
      "기독교와 동성애",
      "역사란 무엇인가",
      "이방인",
      "수수께끼 풀이는 저녁 식사 후에",
      "예술이란 무엇인가",
      "나르치스와 골드문트",
    ],
  },
  {
    major: "정보통신전자공학부",
    bookList: [
      "정보 보안 개론 :한 권으로 배우는 보안 이론의 모든 것",
      "전자기학",
      "SK 그룹 SKCT :SK종합역량검사 :실전모의고사",
      "Eagle CAD 배우기",
      "Principles of communication :systems, modulation, and noise",
      "(이렇게 기막힌 적중률 2017) 정보처리기사 :필기 기본서",
      "(최적합) 네트워크관리사 1·2급 필기 =Network Administrator :최고의 적중률로 합격을 보장하는 국가공인 2017년 최신 기출문제 수록",
      "무선설비기사 =Radio operator :과년도",
      "무선설비기사 :과년도 :한국방송통신전파진흥원 필기시험 집중 대비서",
      "무궁화 꽃이 피었습니다 :김진명 장편소설",
    ],
  },
  {
    major: "건축학부",
    bookList: [
      "현대 건축 :비판적 역사",
      "(10개년) 건축기사 :과년도문제상세해설",
      "건축, 음악처럼 듣고 미술처럼 보다 :인문적 건축이야기",
      "꿈돌이의 라이노 5 :Rhino 건축 모델링 A to Y",
      "건축구조역학",
      "빈자의 미학 =Beauty of poverty",
      "강구조 설계",
      "건축기사 4주완성",
      "건축기사실기 :2017.1.1 출제기준 변경에 따른 예상문제 총정리",
      "(그림으로 알기 쉽게 해설한) 인테리어 도면 보는 법과 그리는 법",
    ],
  },
  {
    major: "전자정보공학부 전자공학전공",
    bookList: [
      "통신이론",
      "Semiconductor physics and devices :basic principles",
      "전자기학 =Engineering electromagnetics",
      "미분적분학 =Calculus",
      "디지털 신호처리:원리, 알고리즘, 응용",
      "CMOS digital integrated circuits :analysis and design",
      "마이크로파 공학",
      "신호 및 시스템",
      "Introduction to microelectronic fabrication",
      "Advanced engineering mathematics",
    ],
  },
  {
    major: "물리학과",
    bookList: [
      "기초전자기학",
      "해석역학",
      "광학",
      "Mathematical methods in the physical sciences",
      "핵 및 입자물리학",
      "An introduction to computer simulation methods :applications to physical systems",
      "Introduction to solid state physics",
      "(과학도를 위한)전자공학",
      "양자역학",
      "Introduction to electrodynamics",
    ],
  },
  {
    major: "벤처경영학과(계약학과)",
    bookList: ["경제학원론 =Economics"],
  },
  {
    major: "사회복지학부",
    bookList: [
      "지역사회복지론 =Community welfare",
      "사회복지법제론",
      "청소년복지론",
      "청소년복지론=Social welfare with youth",
      "사회복지법제론 =Social welfare and law",
      "사회복지조사방법론",
      "해결을 위한 면접",
      "(에센스) 사회복지조사방법론",
      "새로 쓰는 여성복지론 :쟁점과 실천",
      "학교사회복지론 =School social work",
    ],
  },
  {
    major: "정보통계·보험수리학과",
    bookList: [
      "수리통계학",
      "(2018) 보험수학 perfect 정리 :보험계리사 1차시험 대비",
      "표본조사의 이해와 활용",
      "보험수리학 = Actuarial mathematics",
      "Elementary survey sampling",
      "Loss models :from data to decisions",
      "범주형 자료분석 개론",
      "(SOA exam FM) 금융수리",
      "통계적 품질관리",
      "(2018) 보험수리학 Perfect 정리: 보험계리사 2차시험 대비",
    ],
  },
  {
    major: "전자정보공학부 IT융합전공",
    bookList: [
      "통신이론",
      "(먼저 배우는) DSP",
      "(Hayt의) 전자기학",
      "신호 및 시스템",
      "(객체지향 원리로 이해하는) Absolute C++",
      "미분적분학 =Calculus",
      "Engineering electromagnetics",
      "Computer networking :a top-down approach",
      "ARM system－on－chip 구조",
      "(윤성우의 열혈) TCP/IP 소켓 프로그래밍",
    ],
  },
  {
    major: "평생교육학과",
    bookList: [
      "평생교육경영론",
      "리더십 :이론과 실제",
      "101 ways to make training active",
      "E-learning by design",
      "(평생학습사회 실현을 위한) 성인학습 및 상담 =Adult learning and counselling",
      "화성에서 온 남자 금성에서 온 여자",
      "데미안",
      "경영정보시스템",
      "왜 나는 너를 사랑하는가",
      "사랑의 기술",
    ],
  },
  {
    major: "복지경영학과(계약학과)",
    bookList: [
      "(새로 쓴) 원숭이도 이해하는 자본론 :세상에서 가장 쉬운 임승수의 마르크스 자본론 강의",
      "Everyday Talking :abroad",
      "방콕 =Bankok",
      "잉글리시 리스타트 =English restart: basic",
    ],
  },
  {
    major: "기독교학과",
    bookList: [
      "기독교 조직신학 개론 :이해를 추구하는 신앙",
      "기독교 세계관과 현대사상",
      "(아는 만큼 행복이 커지는) 가족의 심리학",
      "종교사회학",
      "하나님 나라 신학으로 읽는 모세오경",
      "한국 기독교의 역사",
      "현대교회사 :쉽게 이야기체로 풀어쓴 흥미로운 역사서",
      "성경을 어떻게 읽을 것인가",
      "철학과 굴뚝청소부:데카르트에서 들뢰즈까지 : 근대철학의 경계들",
      "현대 사회 문제와 그리스도인의 책임",
    ],
  },
  {
    major: "기계공학부",
    bookList: [
      "(최신) 공업열역학",
      "(공학도를 위한) 길잡이 공업수학 문제풀이집",
      "유체역학",
      "(최신) 기계설계 =Mechanical engineering design",
      "연료전지개론",
      "Engineering fundamentals of the internal combustion engine",
      "(Kreyszig) 공업수학",
      "(공학도를 위한) 길잡이 공업수학",
      "Mechanics of Materials",
      "공업재료가공학",
    ],
  },
  {
    major: "글로벌미디어학부",
    bookList: [
      "(최신)디지털미디어 원리 및 프로그래밍",
      "컴퓨터 그래픽스 배움터",
      "(Rosen의) 이산수학",
      "Foundations of algorithms",
      "New media",
      "왜 나는 너를 사랑하는가",
      "(Do it!) Node.js 프로그래밍 :실제 서버로 구동 가능한 코드로 배운다!",
      "Discrete mathematics and its applications",
      "(모던 웹을 위한) JavaScript jQuery 입문",
      "(C언어로 쉽게 풀어쓴) 자료 구조",
    ],
  },
  {
    major: "전기공학부",
    bookList: [
      "전자회로",
      "Digital design with CPLD applications and VHDL",
      "Power systems analysis",
      "(최신) 배전시스템 공학=Distribution engineering",
      "전자기학",
      "최신제어시스템",
      "미분적분학 =Calculus",
      "전력계통 :해석 및 설계",
      "(PSpice를 활용한)전력전자공학",
      "Electronic devices and circuit theory",
    ],
  },
  {
    major: "유기신소재·파이버공학과",
    bookList: [
      "섬유재료학",
      "기능성 섬유가공 =Functional finishs",
      "섬유학",
      "무기화학",
      "(알기쉬운) 통계학",
      "(파비아의) 분광학강의",
      "섬유기초기술 =Textile basic technology",
      "분광학의 이해",
      "Introduction to spectroscopy",
      "(McMurry) 기본유기화학",
    ],
  },
  {
    major: "철학과",
    bookList: [
      "중국철학사",
      "한국철학사상사",
      "(플라톤의) 국가(正體)",
      "감시와 처벌:감옥의 역사",
      "국가",
      "구토",
      "인식론의 역사",
      "대학·중용",
      "사랑의 기술",
      "니코마코스 윤리학",
    ],
  },
];

// 학번별 추천 리스트
export const byGradeList = [
  {
    grade: "12학번",
    bookList: [
      "총, 균, 쇠 :무기, 병균, 금속은 인류의 운명을 어떻게 바꿨는가",
      "왜 나는 너를 사랑하는가",
      "(2주 만에 끝내는) 해커스 OPIc :advanced 공략",
      "경제학 연습 :미시편",
      "국가란 무엇인가",
      "해커스 토익 실전 1000제 :reading :해설집.1",
      "(조민혁의) 합격을 부르는 자소서",
      "세법개론",
      "(친절한) 재무회계 =A gentle introduction to Introduce financial accounting",
      "미시경제학",
    ],
  },
  {
    grade: "13학번",
    bookList: [
      "총, 균, 쇠 :무기, 병균, 금속은 인류의 운명을 어떻게 바꿨는가",
      "왜 나는 너를 사랑하는가",
      "참을 수 없는 존재의 가벼움",
      "데미안",
      "미분적분학 =Calculus",
      "(조민혁의) 합격을 부르는 자소서",
      "(2주 만에 끝내는) 해커스 OPIc :advanced 공략",
      "국가란 무엇인가",
      "진로 탐색 및 직업 선택 :NCS 직업기초능력의 이해와 실습",
      "경제학 연습 :미시편",
    ],
  },
  {
    grade: "14학번",
    bookList: [
      "참을 수 없는 존재의 가벼움",
      "미분적분학 =Calculus",
      "왜 나는 너를 사랑하는가",
      "데미안",
      "총, 균, 쇠 :무기, 병균, 금속은 인류의 운명을 어떻게 바꿨는가",
      "국제법 판례 100선 =International law cases",
      "미시경제학",
      "미시경제학 :수학노트와 연습문제 해답",
      "전자기학",
      "노동법",
    ],
  },
  {
    grade: "15학번",
    bookList: [
      "왜 나는 너를 사랑하는가",
      "데미안",
      "이갈리아의 딸들",
      "참을 수 없는 존재의 가벼움",
      "국제법 판례 100선 =International law cases",
      "위대한 개츠비",
      "(2주 만에 끝내는) 해커스 OPIc :advanced 공략",
      "국제법 판례 100선",
      "진로 탐색 및 직업 선택 :NCS 직업기초능력의 이해와 실습",
      "총, 균, 쇠 :무기, 병균, 금속은 인류의 운명을 어떻게 바꿨는가",
    ],
  },
  {
    grade: "16학번",
    bookList: [
      "참을 수 없는 존재의 가벼움",
      "사랑의 기술",
      "왜 나는 너를 사랑하는가",
      "이갈리아의 딸들",
      "국제법 판례 100선 =International law cases",
      "데미안",
      "미시경제학",
      "(시사와 함께하는) 거시경제학",
      "미시경제학 :수학노트와 연습문제 해답",
      "(최적합) ACA 포토샵CC =Adobe Certified Associate & Photoshop CC :국제인증 자격증",
    ],
  },
  {
    grade: "17학번",
    bookList: [
      "왜 나는 너를 사랑하는가",
      "사랑의 기술",
      "위대한 개츠비",
      "이갈리아의 딸들",
      "멋진 신세계",
      "참을 수 없는 존재의 가벼움",
      "이기적 유전자",
      "데미안",
      "맨큐의 경제학",
      "이기적 유전자 :진화론의 새로운 패러다임",
    ],
  },
  {
    grade: "18학번",
    bookList: [
      "이기적 유전자 :진화론의 새로운 패러다임",
      "역사란 무엇인가",
      "이갈리아의 딸들",
      "참을 수 없는 존재의 가벼움",
      "왜 나는 너를 사랑하는가",
      "이기적 유전자",
      "사랑의 기술",
      "자유론",
      "총, 균, 쇠 :무기, 병균, 금속은 인류의 운명을 어떻게 바꿨는가",
      "데미안",
    ],
  },
  {
    grade: "19학번",
    bookList: [
      "데미안",
      "맨큐의 경제학",
      "(Rosen의) 이산수학",
      "왜 나는 너를 사랑하는가",
      "기독교 조직신학 개론 :이해를 추구하는 신앙",
      "침묵",
      "역사란 무엇인가",
      "일반화학",
      "참을 수 없는 존재의 가벼움",
      "미분적분학 =Calculus",
    ],
  },
  {
    grade: "20학번",
    bookList: [
      "멋진 신세계",
      "역사란 무엇인가",
      "(알기 쉬운)선형대수",
      "(Kotler의) 마케팅 원리",
      "나는 소망한다 내게 금지된 것을 :양귀자 장편소설",
      "데미안",
      "경영학의 이해",
      "(명품) Java programming",
      "미시경제학 =Microeconomics",
      "경제학원론 =Economics",
    ],
  },
  {
    grade: "21학번",
    bookList: [
      "역사란 무엇인가",
      "미분적분학 =Calculus",
      "왜 나는 너를 사랑하는가",
      "위대한 개츠비",
      "올 댓 매너 =All that manner :글로벌매너, 비즈니스매너, 공공생활매너",
      "멋진 신세계",
      "철학의 주요문제에 대한 논쟁",
      "문명의 충돌 :세계질서 재편의 핵심 변수는 무엇인가",
      "맨큐의 경제학",
      "이기적 유전자 :진화론의 새로운 패러다임",
    ],
  },
];

// 외부데이터 활용한
export const byMajorAndGradeList = [
  {
    major: "AI융합학부",
    grade: "12학번",
    bookList: [
      "사랑의 기술",
      "(예제 중심의) 파이썬3: 쉽고 재미있는 프로그래밍 언어",
      "안드로이드 앱 프로그래밍 :T아카데미의 명강의를 한 권에 담았다!",
      "(빠르게 활용하는) 파이썬 3.2 프로그래밍 =Paython 3.2 programing",
      "C programming :a modern approach",
      "Computer systems :a programmer's perspective",
      "미분적분학 =Calculus",
      "(예제중심의) 이산수학",
      "Linear algebra and its applications",
      "GIS 지리정보학 :이론과 실습",
    ],
  },

  {
    major: "AI융합학부",
    grade: "13학번",
    bookList: [
      "(세계 속의)음식문화",
      "몽고디비 인 액션 =MongoDB in action",
      "(쉽게 풀어쓴) C언어 express",
      "Operating system concepts update",
      "Operating system concepts",
      "(나와 상대를 찾아가는 여정) 에니어그램 이론과 실제 :아홉가지 성격유형",
      "군주론",
      "Java의 정석",
      "스크루테이프의 편지",
      "(알기 쉬운)선형대수",
    ],
  },
];
